### ISSUE TITLE
New Module - SSTUAutoDepletionDecoupler

### ISSUE THREAD

**Issue by shadowmage45** [shadowmage45/SSTULabs#111]
Decoupler module(s) (one regular, one radial) that will auto-decouple the part upon depletion of a specified resource and activate a MultiModeEngine switch to activate jettison motors.

**Comment by Jimbodiah** [comment]
So, auto-staging but without mechjeb?

**Comment by shadowmage45** [comment]
Intended for use on single-part SRBs with integrated jettison motors (for the upcoming MSRB module, and for the reworked BPC/LEM parts).  It is the only way to make it work given the stock limitations regarding single-staging-action-per-part and the way multiple engine modules on a part interact.

**Comment by Jimbodiah** [comment]
PS, if you jettison SRBs directly when they are burned out, it could cause problems with low TWR rockets that actually decelerate a bit when the boosters burn out; the boosters will overtake the rockets and get in it's path.

**Comment by shadowmage45** [comment]
How is an unpowered and detached SRB going to overtake a powered rocket during flight?  (SRB jettison motors will be directed to push the SRB away from its attach point, not upward).

**Comment by Jimbodiah** [comment]
Haha... If you have a low-thrust main section with a large fairing on top, it will decelerate rapidly when SRBs stop. If you release at the moment they stop, the SRBs will still have their velocity but the main rocket will be slowing down... the SRBs overtake the main rocket and swerve in front of it. 

The radial decouplers are not strong enough to push large tanks away far and fast enough, they tend to just slide down the main section and slowly drift out before starting to flip (main rockets is then a long way ahead). SRBs fly away and start to flip due to drag; a lot of times they will shoot back towards the center and intersect the center where the main rocket was.

I've seen all sort of crazy shit with things when they detach :)

**Comment by shadowmage45** [comment]
Which is why there is both A: A configurable (in VAB) delay prior to activation of decouple+jettison motors, and B: Jettison motors.

**Comment by Jimbodiah** [comment]
You mean on the new parts?

Is the thrust scaled when you increase the size of the radial decoupler, or is it a fixed thrust?

**Comment by Jimbodiah** [comment]
BTW, could it be the raidals are actually propelling the SRBs forward, causing them to overtake?

**Comment by shadowmage45** [comment]
Yes, for those radial decouplers, they lift up-and-away, rather than straight away (or even down+away).  You can always tweak the force of them, but there is no way to tweak the angle.

**Comment by shadowmage45** [comment]
Hmm.. maybe I should investigate adding the ability to rotate the thrust transforms on the radial decouplers, at least along a single axis, so that you can adjust the direction of the jettison motors a bit.

**Comment by Jimbodiah** [comment]
Nah, just point them outward, as long as they don't go forward or inwards, it doesn't really matter.
