### ISSUE TITLE
Blue Texture

### ISSUE THREAD

**Issue by Jimbodiah** [shadowmage45/SSTULabs#120]
Would a blue Boeing/Delta texture be possible down the line somewhere?

**Comment by shadowmage45** [comment]
I have no desire for more textures at this point in time or for the foreseeable future;  I won't even use 3/4 of those that I have already made (like.. what is the point on the white texture? IDK.. but someone asked for it).  Perhaps if I were able to actually play KSP my response might be different (cannot due to ram limitations and OPM/Kopernicus being a buggy POS crashing my game all the time), but for right now I have no time to spend on creating 'just for looks' stuff.

However, if you would like, I can send you the GIMP project files and you can make them up yourself.  Adding them to the parts is as simple as creating a new MM patch that follows the layout of the existing patches.

**Comment by Jimbodiah** [comment]
haha, i asked for the white one ;). never worked with gimp, but if you could share I'd love to go exploring.

**Comment by Jimbodiah** [comment]
I'd actually like the challenge of figuring out new software, so it would be exciting. Already have 3 textures in mind, if I ever figure it out and it's presentable, they are your's to distribute.

**Comment by shadowmage45** [comment]
GIMP project file for the tank textures:

https://www.dropbox.com/s/3w3uwma8u70ul5l/SC-TANKS.xcfgz?dl=0

Is a pretty big file, so might take dropbox a few minutes for it to upload/be available.

**Comment by lynwoodm** [comment]
I am artistically challenged when it comes to computer graphics. Tattoo designs are a different matter, though.

**Comment by Jimbodiah** [comment]
:)  Took a quick look, lot's to learn I think.

**Comment by shadowmage45** [comment]
Its certainly a process...  I think it took me like 6-8 months of working with it before I really figured GIMP out; and I'm still learning new techniques even now.

Let me know if you need any specific pointers.  And I can also walk you through the process when you get ready to export it (need to apply the specular mask, or it'll be super-shiny in the VAB).
