### ISSUE TITLE
Exceptions/Nulls

### ISSUE THREAD

**Issue by Jimbodiah** [shadowmage45/SSTULabs#147]
I am getting a lot of errors with the last update, and the Kraken now strikes 1:2 whenever I dock. Not sure if the two are related. Logs attached. Right now I am removing all my mods and doing fresh installs to see which one is causing the physics engine to glitch (station spins around, goes into escape velocity and later blows up and slings around).

http://kerbal.nl/sstu_null.rar

**Comment by shadowmage45** [comment]
Whatever is causing the 'Input is null' spam is -not- from SSTU.

Please clean that up/fix that from whatever mod it is, and re-test.  

There is only one SSTU related exception, and it is something that should not be able to happen (either part or vessel being null while in flight), so something else is even causing that.

As with other issues, to even begin investigating, I need a minimal test case to duplicate the problem.  This means SSTU + stock parts only, and a simple ordered list of steps needed to trigger the problem.  If you cannot duplicate the problem with only stock/SSTU parts, then chances are the problem lies elsewhere.

**Comment by Jimbodiah** [comment]
The Nulls are coming from the WildBlue DSEV mod, but I noticed the SSTU exception in there while looking. I have been running that mod for ages and there were no updates, yesterday I had nothing but Krakens since installing the new SSTU patch, so I thought they might be related due to that exception in that log. I'm running a new vanilla install now to see which mod does what.

**Comment by shadowmage45** [comment]
Thanks for taking the time to investigate, and thanks for the logs.

There might well be a problem with the parachute module, I haven't tried doing docking stuff recently.  If you can find a way to replicate the null-ref error on a clean install/simple setup, that should at least give me a place to begin investigating.

**Comment by Jimbodiah** [comment]
I think it's a combination with another mod, trying a new one each time to see which one replicates it. I've also asked Angel to check his mods for those Null errors and also some other things and have removed that mod for the meantime. Sorry this is vague, hopefully I can put it to rest either way.

**Comment by shadowmage45** [comment]
This appears to be caused by the parts rigidbody being null for the root part during the first update tick.

```
[LOG 10:58:39.964] part rigidbody==null!
[EXC 10:58:39.967] NullReferenceException: Object reference not set to an instance of an object
    SSTUTools.SSTUModularParachute.updateParachuteStats ()
    SSTUTools.SSTUModularParachute.updateFlight ()
    SSTUTools.SSTUModularParachute.FixedUpdate ()
```

I will put in a check/catch for this, though I find it interesting that it can happen at all.
