### ISSUE TITLE
SC-TANK-MFT - Fairing-disabled mount types can still have the fairing enabled

### ISSUE THREAD

**Issue by Jimbodiah** [shadowmage45/SSTULabs#180]
The fairing on the new MFT-A (mount side) does not start from the tank, but a bit below it, leaving a gap. This is only if no mount is chosen (flat bottom). The mounts all have good fairings.

Also the length in career mode seems to have changed as my builds now have shorter max lengths (still low in the techtree).

**Comment by shadowmage45** [comment]
Pics?  What mount / tank length?

Career mode - yes, there are limitations in career mode; the full tanks don't unlock until much later.

**Comment by Jimbodiah** [comment]
If you scroll through the mounts and go back, the fairing then does join to the next stage. I'll test with a new build instead of existing ones.

Career mode: I had longer tanks with the last version, no biggy, just wondering if tech-level was changed.

**Comment by shadowmage45** [comment]
Fairing - hmm, if it persists, let me know -- I might need to take a look at the fuel tank-fairing interaction code again.

Have not changed the tech-limits in those parts in quite a few releases, though I might have changed something in the plugin side of things that made them actually take effect.  I'll scroll back through my change-log to see if/what/where things got changed.

**Comment by Jimbodiah** [comment]
NP on the  tech change, I just noticed it. Two tanks works the same as one big one, so no issue at all.

**Comment by Jimbodiah** [comment]
OK, just found out that the mod did not make them shorter, but sometimes I can make them longer than the techlimit would allow. I don't know in what situations though, sometimes I can just adding length, sometimes it stops at a certain limit. I get the same with MechJeb functions sometime, so I doubt it's coming from SSTU.

**Comment by shadowmage45** [comment]
Re tech-limits -- I'm betting that if you go to a small diameter, you can select a very long tank, and then increase the diameter of the tank and it will keep the now too-long of a length.

Will have to revisit how I do the length-limitations for the tanks, to perhaps limit them to multiples of the tank diameter rather than a strict height.

**Comment by blowfishpro** [comment]
I would't worry too much about tech level size limits on the tanks.  Stock seems to have this idea that bigger = more advanced, but (1) that doesn't actually make sense and (2) With the variety of RL-ish engines SSTU provides, there's no way to keep that paradigm (unless you really think the Merlin 1D should be unlockable before the F-1).

**Comment by Jimbodiah** [comment]
All SSTU engines are unlocked near the end of the tree, so you get them all at once.

**Comment by shadowmage45** [comment]
Good point on the tech limits; at least as far as length goes.  Also goes more towards part reduction so you should never have to stack tanks.

Engines -- only because I haven't gotten around to doing tech-tree balance on...anything yet.  That would be what #88 is about :)

**Comment by Jimbodiah** [comment]
Yeah, the excel sheet :) I gave you a list of where they might go a while back, just not the actual names in the cfg I believe.

**Comment by shadowmage45** [comment]
Reading more on your description of the issue -- this is actually caused by the fairing being usable with 'None' for the mount type.  

The fairing should be completely disabled and unusable (manually or otherwise) if 'None' or any other fairing-disabled mount is currently selected (e.g. Saturn-V, SLS, Direct mounts).

Updating description and stuff appropriately, and will investigate this for a fix shortly.  Need to get that fairing module interaction sorted out finally; its close, but there are obviously still a few points to cleanup.

**Comment by shadowmage45** [comment]
Closing this ticket for now as I have not been able to duplicate this issue, and have updated the fairing interaction code multiple times since this was opened.

Please let me know if this is still a problem, and will do some more investigation during the pre-release cleanup period.
