### ISSUE TITLE
SC-B-SM panels no longer tracking or producing Ec

### ISSUE THREAD

**Issue by Jimbodiah** [shadowmage45/SSTULabs#191]
The C-SM panels no longer seem to work.

See log files

http://kerbal.nl/sstu/sstu_c_panels.rar

**Comment by shadowmage45** [comment]
Hmm.... strange, as I did not change anything regarding the solar panel module or config setup, but will do some testing to verify that it still works.

**Comment by Jimbodiah** [comment]
Now mine produce Ec again. Had three launches/rebuilds where it did not produce any Ec. I sweat I am not nuts! ;)

**Comment by Jimbodiah** [comment]
Had it again, during a time-warp the craft ran out of electricity while the sun was up, panels stopped working (no Ec and not following sun). New logs attached.

http://kerbal.nl/sstu/sstu_c_panels_02.rar

**Comment by shadowmage45** [comment]
Well, for one, they are -not- tracking panels.  You need to make sure you are oriented properly.  The side with the white hardware on it will not generate electricity.

Properly rotated, the fully gold side is towards the sun, and it does generate EC:
![screenshot0](https://cloud.githubusercontent.com/assets/1503399/12527490/9785ff74-c139-11e5-8a27-0a83d24217ae.png)

If the wrong side is facing the sun, you will get no EC generation.  
![screenshot1](https://cloud.githubusercontent.com/assets/1503399/12527491/a45c3416-c139-11e5-9435-2dc1d554eaf3.png)

This is intentional and not going to change (unless someone can present some evidence towards the rear-side of a solar panel generating EC, or that the soyuz panels are double sided;  either may be the case, but I have not seen or read anything pointing towards such).

**Comment by Jimbodiah** [comment]
Arrrgh... I am mixing up series... I meant the Orion SM... B series... omg I swear my brain is fried...

**Comment by shadowmage45** [comment]
:)  It happens, I'm starting to get them mixed up myself... they're all out of order :)

I have not noticed any problems with the SC-B-SM solar setup; I just finished quite a few mun-return-re-entry tests while using it, and did not have any problems during any of the testing runs.

However, if you are talking about this: 
[LOG 00:09:59.937] DragCubeSystem: Rendering procedural drag for SSTU-SC-B-SM2

part in your log -- I'm afraid I cannot help you with any kind of custom patched/cloned/etc parts.  Please try it with the as-shipped parts and configs, with a minimal mod-setup, to ensure that there are no other mod conflicts, or any problems with the custom patching/setup.

I am only seeing one SSTU null-ref in that log, and that is the same parachute-module related one from #147 (that seems to be a mod conflict, as I cannot duplicate it on my end).  If you can figure out what particular mod(s) are causing that one (or verify that it occurs on an otherwise stock setup), I can set it up on my end to attempt to clean that one up and make sure it is not the cause.

**Comment by shadowmage45** [comment]
Well, I have finally seen the same parachute-related null-ref pop up in my log, though I've not yet narrowed down the exact steps to duplicate it.  Will work on getting that cleaned up for the next release, and see if that fixes your problem (did not seem to effect the solar panels on my end.. but KSP does some inconsistent stuff sometimes).

**Comment by Jimbodiah** [comment]
As you noticed I am walking up against a few KSP stock bugs while trying to test SSTU, so every time I come across something now I am afraid to post about it as it's probably just more stock bullshit I'm dealing with. 

The B-SM clone has lowered SAS and increased ISP (NF prop style) to simulate some shuttles I used for tourist trips in career mode as I just can't muster the energy to make a complete setup with stock/real-life parts that will resemble anything I had running in career before I wiped every single ship to go back to vanilla.

I just can't be bothered to rebuild that entire setup with stock parts to do some bug testing, that might point to yet another KSP stock bug. So I will take all the bugs while it lasts and just run full fledged modded setup as of tomorrow. If I get tired of all the mods (or mostly KSP) freaking out, I think I will just uninstall this game and move on. 

It seems KSP can not be bothered to fix all the major issues and they keep dangling that 1.1 carrot in front of us like that will solve all the problems. What I see in the dev notes posts, they have even more issues with their 1.1 version than there are in 1.0.5. Not holding my breath anymore that they will ever fix it.

Sorry for the long sob-story ;)  Just tired of stock KSP hassles right now. I can understand mods giving problems, but if the game itself is 90% of the problem, it's just hopeless.

**Comment by shadowmage45** [comment]
No worries on the SM patches, it doesn't _sound_ like that should effect anything with the solar panels.   The mod list didn't seem to have anything in it that would cause a conflict either, though I've been surprised in the past.  I'll go through the logs a bit more in depth tomorrow while I'm working on doing coding/bugfix stuff to see if I can spot anything else worrying. 

Does it seem to happen under any particular set of circumstances, or so far at random?

I understand your frustrations though, and I don't mean to be adding to them.  And I do appreciate the bug reports that you do submit, as most of them have been valid problems and have certainly increased the quality of the mod.

Yes, KSP has its own share of problems which are hard to avoid; and they are only aggravated further (or made more apparent at least) by mods and mod code (this one included), who often try and push the limits and work around the stock setups.  Squad has mentioned that they've cleaned up quite a few outstanding bugs in their update, though I haven't seen much detail regarding the specifics.

Nothing wrong with a break until 1.1.x is released and checking back in on it if you are burned out/fed up.   I hear Elite Dangerous/Horizons is good for killing a month or two :)

**Comment by Jimbodiah** [comment]
I dont mind issues with SSTU as I know beforehand it's a mod and in development.

Anyway. the solar panels seem to stop after going in and out of time warp several times, it takes a while for it to manifest.

**Comment by shadowmage45** [comment]
Have you had any more luck tracking down how to duplicate this problem? (And is/was there anything in the log when you noticed these problems?)

Don't want to leave this problem hanging around if it is in fact a problem, but I've still been unable to duplicate it on my end.

**Comment by Jimbodiah** [comment]
Have not noticed it, but I've not used the Orion SM for long missions since the initial report here. On short trips it was never an issue and it occured after several tome warps. Close the issue, if it comes up again I will post it here.

**Comment by Jimbodiah** [comment]
I had this bug again on a long mission with the Orion SM and timewarping. After a few timewarps the panels are fixed in their zero postion, do not track the sun and do not generate Ec when you point the orion towards the sun.

logs:  http://kerbal.nl/sstu/orion_panels.rar

**Comment by shadowmage45** [comment]
Thanks for the log; I'll attempt to do some testing on this in the next week or two.  (really wish I had more time that I could actually test stuff; sadly most of my dev-time comes at work, where I cannot run KSP to test things).

**Comment by Jimbodiah** [comment]
It's always after a physical time-warp it seems. I did the same mission with only normal time-warp and it did not occur.

**Comment by shadowmage45** [comment]
I still have been unable to duplicate this issue.  I noticed from your logs that you are using a rescale mod (K365) (along with a few others that might cause problems).

Have you had this issue manifest on a stock+sstu install?  And when the problem occurs, does it effect stock solar panels as well (they both use vessel.solarFlux to determine energy output; though the stock module does not use it for tracking)?

Looking over the modules' source code, there is only one thing that would cause the panels to stop tracking and producing EC while actively deployed -- the vessel has a vessel.solarFlux <= 0.  This could be caused by any number of factors/mods that interact with the stock solar system.

Looking more and more like this is a bug with one of your other mods, but still need a method to reliably reproduce it in order to even be able to test it.

**Comment by Jimbodiah** [comment]
Same issue with stock install. The first time I reported this issue I did not have K365.

**Comment by shadowmage45** [comment]
Strange... I did a Duna return mission last night, with tons of regular + physical time warp (for testing of heat-shields at duna return velocities), and did not encounter any problems with the solar panels; this was over 700 kerbal-days worth of regular time-warp of different factors, and several 5+ minute stretches of physical time warp for some burns.

Chances are (if it is not a bug with another mod) that I'm not going to be able to track this down without some concrete and repeatable steps to recreate the problem.

Going to keep it open for now, and hopefully you can come up with the actual steps for recreation so that I can finally get it squashed.
