### ISSUE TITLE
Craft Loading

### ISSUE THREAD

**Issue by KingBabar** [shadowmage45/SSTULabs#2]
When loading the LC3 and LC5 craft in the VAB the previous craft will remain and attachment nodes will not work.

**Comment by shadowmage45** [comment]
Thanks for the report.

Apparently I have broken some of the craft in one of the updates (likely due to changed attach node names or similar), so will have to redo them at a future point.

Will likely remove them for the time being (until I'm done breaking things), and look at doing up better examples in the future.  Will probably hold off until I have done the re-balancing pass on all the parts, as I would just need new examples then anyhow.

**Comment by shadowmage45** [comment]
Have updated/replaced example craft with the most recent release.
