### ISSUE TITLE
SRB nosecones don't switch with symmetry

### ISSUE THREAD

**Issue by blowfishpro** [shadowmage45/SSTULabs#204]
When switching the nose type on one SRB, symmetry counterparts don't change with it.

**Comment by shadowmage45** [comment]
Thanks for the report.

The existing SRBs use an old mesh-switch plugin that I developed for the LanderCore series of parts; it does not support any kind of symmetry updating.

This will be fixed with the upcoming MSRB part, as it is using a custom plugin that properly handles symmetry updates (and all other things SRB related).
