### ISSUE TITLE
dV values in MJ for 2nd stages

### ISSUE THREAD

**Issue by Jimbodiah** [shadowmage45/SSTULabs#208]
I've been testing this a bit, but the dV shows by MJ is off by a factor of 8x; it shows 4000+ dV in the second stage, but an orbital prograde burn of 600m/s will empty the entire tank. This is with both LF/Ox and LH2/Ox on all four SSTU tanks. On stock tanks+engines I get accurate readings on both stages.

**Comment by Jimbodiah** [comment]
This problem comes and goes when I restart KSP, it might be a stock issue combined with something in SSTU as when it happens the stock tanks still give the correct values. Next time I see it, I will upload the logs.

**Comment by shadowmage45** [comment]
This is something that is on MJ end of things -- I cannot control or fix MJ calculations, period.

Also -- make sure the root part of the craft is part of the last stage, or it will give incorrect values. (Again, a MJ problem).

Generally though, it gives me very consistent and usable values for stuff; except where there are known bugs in the MJ implementation (mostly involving decouplers).

**Comment by Jimbodiah** [comment]
It might indeed be a combination of things, but it's not consistent in behavior which is annoying to try to find out which end is causing it.

**Comment by shadowmage45** [comment]
Going to re-open this one for now... but going to need a lot more information to start investigating properly.  There might be some changes that I can make to the decoupler parts that could help MJ with its staging calculations (there are a bunch of config fields related to staging that I'm really not sure what they do... but seem to be used mostly for decouplers, so they might be important).

1.) MJ version
2.) Minimal craft setup to cause the problem using SSTU parts -- specifically which parts / combination of parts, in what staging order, and with what root parts, causes the issue.
3.) Can the problem be duplicated when substituting stock parts for decouplers?
4.) Can the problem otherwise be duplicated using stock parts?

**Comment by Jimbodiah** [comment]
1.) Latest version 2.5.5.0
2-3.) will test further and get back
4.) stock parts functioned normally at the time when I was getting weird results with MFTs

**Comment by shadowmage45** [comment]
I have seen a bit of this in my games recently, but it is very inconsistent.  Off-times I can 'fix' it by pulling parts of the craft off and putting them right back in place.

Will see if I can find a reliable test-case / means to duplicate it, and attempt to narrow down the interfering parts.

**Comment by shadowmage45** [comment]
Still have not been able to figure out the methods to duplicate this problem.  It seems to manifest most often when I use the interstage petal adapter and interstage decouplers (both parts with multiple internal decoupler modules).  Could be some MJ problems related to multi-decoupler parts; could also still be some staging-order related stuff from my parts' configs.... not really sure.

**Comment by shadowmage45** [comment]
Have added staging offsets to all decoupler enabled parts;  that is about all that I will be able to do towards fixing this problem.

Hopefully the cleaned up staging interface with 1.1 will help MJ fix its end on this problem.

**Comment by Jimbodiah** [comment]
I've not seen the problem with the last few releases, so perhaps the issue is gone. With the latest release of MJ the TWR also seems more consistent.
