### ISSUE TITLE
RS-68: Roll control on turbopump exhaust

### ISSUE THREAD

**Issue by blowfishpro** [shadowmage45/SSTULabs#229]
Would it be possible to allow roll control on the RS-68's turbopump exhaust (the larger port), as in the real thing.  I think this is what it would require:
- Separate out the nozzle into its own object.  This would require minor texture work.
- Add thrust transforms to both exhaust ports with their own engine module
- Add gimbaling to the larger (supported) nozzle with the appropriate axis constraint set up
- I'm not sure if it's possible to set the gimbal module to only respond to roll input (since I'm not on my modding computer right now).  I don't think so but maybe.

I know that the single axis gimbals have caused some odd behavior on the RD-107/8, but I think it wouldn't be nearly as bad in this case since the main pitch/yaw gimbal is handled by the main thrust chamber while the exhaust port would only provide a tiny bit of control needed for roll.

**Comment by shadowmage45** [comment]
Have this implemented so far as:
- Added thrust transforms to both exhaust nozzles
- Added gimbal transform with target for the LH2 exhaust nozzle
- Set up constraint to rotate the exhaust transform along only a single axis towards the gimbal target
- Geometry is static, merely going to cheat it with vectored thrust;  would require several hours worth of model work / rebaking / retexturing for minimal return on effort.
- Chose 10' as a gimbal range for the roll nozzle, much more and I would need to rework the geometry.
- Chose 50kn for the exhaust nozzles testing thrust.  Will likely increase it, see below.
- There is a pretty bad thrust differential between the arms resulting in a constant pitching (or yaw depending on orientation) input.  The roll nozzle exerts more thrust in the direction of travel due to its downward angle, whereas the other nozzle points more towards the COM.
  - Possible solutions include either angling the roll nozzle outward, and/or angling the other nozzle a bit more downward.
  - A second solution would be to add a -third- engine module for the second exhaust, so that the thrust differential could be balanced.  This would be a last resort if I cannot solve it through other means.
- At 50kn of thrust (25 for each nozzle), the roll authority is minimal, even on fairly small test craft.  It only starts to work when you get down to very minimal fuel / mass for the vessel.
- At 50kn of thrust (25 for each nozzle)  there is a noticeable yawing component associated with the roll input, likely due to the asymmetrical thrust / single vectored nozzle.

Will play around with this a bit more throughout the week, see if I can clean up the differential issues and increase the roll authority.

**Comment by blowfishpro** [comment]
Thanks for looking at this!  If it proves to be impractical I completely understand.

I wasn't expecting a lot of roll control - mostly maintaining attitude rather than providing full rotation control.

The yaw moment makes sense, though I'm surprised it's so pronounced.  The real Delta IV probably has control software that adjusts the main gimbal to compensate.  Not really practical in KSP of course.

**Comment by shadowmage45** [comment]
Upped thrust to 80kn, which gave it enough roll authority to... well.. be functional :)  Might need to bump it up a slight bit more;  I really have no clue what is appropriate for it, and could not locate any hard information during an initial google search, so will be open to feedback on this after some testing.

Adjusted the transform default orientations a bit.  This minimized the pitching input... will be hard to notice on fully loaded craft.

Yaw coupling is still present, but you won't notice it if you have MJ fly or tell SAS to fly prograde.  Easily countered by a tiny bit of input from the main engine gimbal.

Have not tested it yet in a 3-core/etc setup, but I expect it likely still works fine.
