### ISSUE TITLE
Orion SM fairings do not detach/disappear

### ISSUE THREAD

**Issue by Jimbodiah** [shadowmage45/SSTULabs#252]
When you have the Orion SM place on a petal adapter, the SM fairings (bottom part) will stick to the pedal when the SM is released. It will stay on top of the petal until you release the inner node. This looks funny when you do an Apollo style setup where the CM/SM detaches, turns around and docks with the lander.

**Comment by shadowmage45** [comment]
Intentional -- you need to set the bottom-fairing # of panels to > 1, and it will jettison them to the sides when the SM detaches.  (this is the same for all lower-fairings; engines, mounts, ICPS, etc).

There is no (easy) automatic way to tell what parts are mounted below and whether the fairing should jettison or not, so it is left to the user to configure things for their current use/setup.

Let me know if the problem persists when you set the # of panels to > 1.
