### ISSUE TITLE
New Part: Scaleable Inline SAS

### ISSUE THREAD

**Issue by SuDragon2k3** [shadowmage45/SSTULabs#260]
Could we have a scaleable SAS ring to go with the scaleable tanks?

**Comment by shadowmage45** [comment]
I'm not a fan of the magic nature of SAS to begin with, so I will likely not be making any stand-alone SAS parts.  They especially do not belong on rockets; and at no point should the answer ever be 'just add more SAS'.

The closest I would come to these would likely be the Modular Service Modules that I've been planning; these will have rcs, reaction wheels (small), and other various bits for general purpose spacecraft.

**Comment by Jimbodiah** [comment]
SAS is just the command module, like with the two upper stage tanks. Don't know if he wants reaction wheels as well?

Any info on the modular SM you had in mind? Or is that more for the satellite parts later (which is basically a modular SM with science)? I think this is what SuDragon could be after as well; sort of a drone core instead of a manned SM.

**Comment by shadowmage45** [comment]
Modular Service Module requires the ModuleSwitch stuff that I've not yet implemented (so that you can swap out your solar panels for a fuel cell; or the science bay for more fuel; or the food bay for more science; or any number of bays for more payload.

I wouldn't expect to see anything on it for at least a few more months.

**Comment by Jimbodiah** [comment]
OK, thanks!!!

**Comment by shadowmage45** [comment]
I would be more inclined to a do a procedural probe-core only; but even that might be better done as part of the MSM line of parts -- could be done as a 'short' service module with no propulsion unit; one quadrant for the probe-core, while leaving three quadrants for battery/science/propellant/whatever.
