### ISSUE TITLE
Modular Radial Booster Decoupler

### ISSUE THREAD

**Issue by Jimbodiah** [shadowmage45/SSTULabs#269]
The block that attaches to the main core is always the same size and no longer scales with the diameter. This means it is huge on smaller cores (<2.5m).

Also the diameter of the rings does not match any step sizes on booster diameters, it is always off by a little bit (0.05 on most cases I've seen)

**Comment by blowfishpro** [comment]
The block not scaling also means that the pylons on the rings often don't touch the parent part at small sizes.

**Comment by shadowmage45** [comment]
Not much I can do about this -- it has to scale the way it does so that the rings have any chance of actually surrounding the attached part -- if I scale the base, the rings will be offset from the physical attach point (as the base is the part with the surface-attach collider), and then it looks terrible as nothing lines up (this isn't even touching on the problems of stock surface-attach-node position updating).

**Comment by Jimbodiah** [comment]
The base always used to scale properly, only 2-3 releases ago did it suddenly stop scaling and the rings not match the boosters anymore.

**Comment by shadowmage45** [comment]
After reviewing the change-log/commits to that plugin, no code relating to base scaling has ever existed in that class.  You might be imagining things?

(the most recent code changes for that module, nothing in there regarding scaling of the base)
https://github.com/shadowmage45/SSTULabs/commit/bcf2f088d6c1acd0be86a078217c4c7cb3d81e56
(the prior changes to that were in the middle of Feb, and didn't contain anything related to base scaling either).

IIRC the base has never scaled, and the little arms have always been a bit off when scaled to smaller sizes.

However, if you can find the version that the scaling was working in, I'll go and look through the change-log/commits to figure out what got broken.

**Comment by Jimbodiah** [comment]
Is it possible the block was just smaller in previous versions? Boosters used to fit quite close up to the main core, now they stick out a lot on smaller cores, to the point of looking funky.

**Comment by shadowmage45** [comment]
Possible, yes... I had to re-export the part model a few releases back (when I fixed the thrust transform orientations and added the thrust differential stuff), and it might have had some unity-side changes that did not get re-done properly (part of why I despise the blender->unity->ksp production chain; needs to just go blender-> ksp, and remove the unity garbage in the middle).

**Comment by shadowmage45** [comment]
I will investigate the model tonight to see how the colliders/part positions are lining up with the scaling;

Will also investigate scaling of the base with the overall model size; pre-warning though, that this will 'break' any existing craft using the part as it will most certainly reposition the attach rings relative to the new scaled base positioning.

Will also consider adding a slider control for offsetting the rings inward/outward in case of collider alignment issues (as the precise placement of the part in the ring depends on the collider of the both base and the part being attached as well as the part-being-attached's surface-attach node position).

**Comment by shadowmage45** [comment]
So yes, apparently the collider did get mangled by unity during the last exporting of the model.

Have fixed the collider, and since I was already reworking and re-exporting the model (which is what I was trying to avoid...), I have added in a root transform that can be used to scale the base model as well as the rings all in one pass.

Will add in the attach-node repositioning code to the plugin, and change it up to use the root transform for scaling the entire model.

**Comment by Jimbodiah** [comment]
Thanks Mage!
