### ISSUE TITLE
Service module fuel cells

### ISSUE THREAD

**Issue by blowfishpro** [shadowmage45/SSTULabs#280]
Would it be possible to add fuel cells to the service modules?  Particularly important for the Apollo SM since it has no solar panels.

**Comment by shadowmage45** [comment]
Currently the fuel-cell is in the CM.  Can have it either in the SM or in the CM;  I left it in the CM so that it could be used to replenish EC during re-entry;

Perhaps I should just move it to the SM though and increase battery capacity of the CM.

**Comment by blowfishpro** [comment]
Either way works, I guess.  I thought I checked the CM, but I guess I missed it.

**Comment by shadowmage45** [comment]
Have moved the Fuel Cell module out of the CM/CMX and into the SM.  Also increased EC capacity of the CM/CMX by 150 units each (450 for CM, 600 for CMX).

**Comment by lynwoodm** [comment]
I thought if you put converters in the same parts with an integrated engine causes the engine to fire before it's staged?

**Comment by shadowmage45** [comment]
Nope, that has been fixed for awhile (1.0.2?).  Thankfully :)

Yes, the BaseConverter used to trigger -every- stageable module on the part when it was initialized; decouplers, engines, everything.  However I have not seen that problem with any parts in recent versions (and if I do ever see it again.. well.. I've already got a custom converter module written up that I can use :))

**Comment by lynwoodm** [comment]
I only bring it up, because I put some converters in some pods that had integrated engines with 1.0.5. Granted, they weren't power converters (TAC-LS carbon scrubbers and water purifier), but all of them activated on the pad. Then I found the thread in which you discussed this very thing a while ago. Maybe it was just a TAC LS issue, not to sure. 

But, I kinda shy away from putting a module manager patch to any kind of converter in pods with integrated engines since I read that. I just use a stock battery to put the processes on and slap it on the hull. I even made a closed loop system for food as well. But, if you say they fixed it, then you'd know more than I would. Let's hope it turns out okay! :)

**Comment by blowfishpro** [comment]
Just to clarify - is it intentional that the service modules that have solar panels (Soyuz and Orion) don't have fuel cells?

**Comment by shadowmage45** [comment]
Yes; as far as I'm aware those SM's don't come with fuel cells IRL.  And with this being KSP... people can always add them on if they really want (though...they'd need to patch in a MP driven fuel cell...)
