### ISSUE TITLE
SC-TANK-MFT - Adapters on bottom are placed incorrectly

### ISSUE THREAD

**Issue by blowfishpro** [shadowmage45/SSTULabs#285]
Create MFT-A or MFT-B in the editor.  Set mount type to one of the adapters.  It is offset from the actual bottom of the model.  This is not the case for selecting an adapter as the nose.

**Comment by shadowmage45** [comment]
Does this effect all mounts/etc on the bottom, or only specific mounts/adapters?

**Comment by blowfishpro** [comment]
Only the adapters, it seems.  Mounts are fine.  The Soyuz tanks seem fine too.

**Comment by shadowmage45** [comment]
As I changed quite a bit regarding nose and mount positioning (to support the LC-FUEL model stacking), I've likely got some incorrect offset data entered for those models or am otherwise calculating the offset improperly for inverted parts.  (likely the latter as for the LC parts it did not matter which way I calculated the offset as it was half of the tank height).

Will investigate this tonight/tomorrow for the next release.

**Comment by shadowmage45** [comment]
Indeed, I was setting the offset improperly for models that were inverted on the bottom of the tank.

Fixed in dev; will be available with the next update.

**Comment by blowfishpro** [comment]
Now the adapters are correct but the mounts are not.  Should this be re-opened or should I make a new issue?

**Comment by shadowmage45** [comment]
Ruh roh... re-opened.

Sadly I'm right in the middle of doing the resource-tank update stuff (nearly there) so might not be able to post an fixed release until later this evening.

**Comment by shadowmage45** [comment]
Note to self:  Test other related things after you 'fix' something :)

**Comment by shadowmage45** [comment]
Update published, all seemed to work well (mounts, adapters, noses, etc)
