### ISSUE TITLE
SC-GEN-RBDC Radial Booster Decoupler - Locked max size on right-click (1.1 Dev Release)

### ISSUE THREAD

**Issue by Theysen** [shadowmage45/SSTULabs#286]
Once placed on any part right clicking to edit results in jumping to 10m diameter and locking. Rest can still be edited, only diameter is locked up. Disable Staging doesn't hide or reenable the staging button.

Tested in sandbox on 32bit / 64bit (stock + SSTU & dependancies)

Logs
[https://www.dropbox.com/sh/tufx9sa8zzhahab/AACitQ7NLA6b0SY7F9ZWtVg0a?dl=0](url)
(^ strangely clicking this results in a Github 404, I had to mark it and then copy it?)

**Comment by shadowmage45** [comment]
Thanks for the report, and including logs! :)

Fixed in dev code.  Was incorrectly passing the max diameter for both the min and max diameters when setting up the float-slider validation parameters.  Hence when you interacted with the part it 'fixed' the 'incorrect' value to what it thought was right.

Changed to properly use min diameter and tech-limited max diameter for validation parameters.
