### ISSUE TITLE
SSTUDecoupler Module - 'toggle decoupler staging' bug

### ISSUE THREAD

**Issue by riocrokite** [shadowmage45/SSTULabs#3]
when in editor I can switch off decoupler option on lander cans, however I cannot switch it back on.

**Comment by shadowmage45** [comment]
Thanks for the report.

I will likely be removing the decoupler module from the pods before public release; the physics-less procedural decoupler part is intended to be the replacement (and allows for proper dV calc through MJ/KER).

However, if I do leave them in place I will make sure I fix up the module they are currently using;  in its current state the code is a bit of a mess because I was trying to fix some of the stock node / fuel flow issues, and never bothered to clean up the code when I was done testing things.

**Comment by shadowmage45** [comment]
Have removed decoupler module from LC pods, and added the second (lower/fuel tank) node as an optional toggle-able node (right click on the part and click 'add node').  Parts will now by default attach to the engine-attach node; things intended for the outer ring/fuel tank node will need to have the node manually added prior to be attached.

Should resolve issues with wonky decoupler staging stuff, and add a bit cleaner separation between the engine and outer node.

Will have this in place for the next test release.

**Comment by riocrokite** [comment]
cool, nevertheless this switchable decoupler module plugin might be very useful for other modders so it would be cool if it worked :)

**Comment by shadowmage45** [comment]
Unfortunately, it does not work properly, at least as far as MJ/KER are concerned.  When you remove the part from the staging list, you lose control over where MJ/KER -thinks- that a stage break occurs, and it will completely fubar dV calculation for that vessel (or can, depending upon where the rest of the parts think they are in the staging sequence in relation to the now-removed decoupler).

What I really need to do is work on a proper solution to dynamic module switching; so that when you turn the decoupler off, it is actually fully removed from the module list.

**Comment by shadowmage45** [comment]
Have removed decoupler modules from the pods for now, in favor of the physics-less procedural decoupler.

Relabeling this issue to a more descriptive 'SSTUDecoupler module staging issues', to remind myself to fix up that module before I use it anywhere :)
