### ISSUE TITLE
SSTU-SC-A-SMX-Station Service Module/Configurable containers feature request

### ISSUE THREAD

**Issue by Domfluff** [shadowmage45/SSTULabs#334]
The Progress-like unmanned module could be pretty useful, but is limited at the moment by the available configurations (i.e., it can currently only transport fuel and EC.)

Thematically, it makes sense to me that this could carry USI-LS Supplies at the very least, but KIS Inventory space also makes sense for this part.

Therefore, I'm requesting that this part allow for Inventory configuration, and that the configurable containers in general allow for Supplies and possibly Fertilizer to be carried, to allow for greater integration with USI-LS.

**Comment by shadowmage45** [comment]
Definitely within the realm of possibility, and most is actually already on my TODO list in a slightly altered form; but keeping it here as its own issue has a higher chance of me seeing it when I'm working through the updates and fixes for a release.

I intend to add a few more resources to several parts' container setups to more fully support the fuels that I currently use (all stock + lh2, nto, aerozine), and as a separate note I also have a to-do for better LS integration.  These would apply fairly globally to most/all of the container enabled parts rather than just the SMX; though that part has been mostly useless since its creation in a stock game, and does sorely need some attention.

The reason those don't exist currently is because those resources are not necessary or available in a stock game, and belong in the USI-LS patch, TAC-LS patch, or KIS-integration patch, and I have not yet been able to do much testing or work on the LS or KIS integration.  The USI/TAC-LS support that exists currently for the pods was provided by other users who were more familiar with how those mods function and what values the different resources should have.

KIS, I thought, should have been auto-supported on all containers through its patch, but I will certainly look into it when I am working on the mod-integration patches.

**Comment by Domfluff** [comment]
I'm more than happy to throw together some USI-LS patches for your station parts - they'd need supplies and recyclers at least, at varying levels, and some bonuses to habitat time. That's all easy, assuming I can find some sensible numbers to aim at. Whether they include processing fertilizer into supplies (I.e. growing crops) is a different question entirely, and I suspect they probably shouldn't without some kind of dedicated module.

**Comment by taterkerman** [comment]
Dunno where to put this, but the colliders for the SMX are a little wonky. I was trying to make a rover out of it (to ram solar panels on the runway to test them for colliders, and it was a nice, long shape I figured I could slap wheels on and be done (rovers are a PITA)). I noticed the wheels were all over the place in symmetry, some even attaching well outside the SMX itself.

**Comment by shadowmage45** [comment]
Yea stock code does some funny things with mesh-analysis for surface attaching things.   It is far worse on parts with multiple colliders and complex shapes, and absolutely terrible about asymmetric shapes.

I'll take a look at it, but there is likely nothing that I can do as it is all stock code.

**Comment by shadowmage45** [comment]
SC-A-SMX resource availability fixed up with the upcoming SSTU-OptionalPatches config set; it adds all USI resources to the SMX.  (Other resource sets will need to come through other patches, and as I don't use other resource-adding mods, they'll have to come from someone else familliar with the mods and their resource uses).

Will be available with the next release.
