### ISSUE TITLE
SSTU removes LV-N engine?

### ISSUE THREAD

**Issue by Mogball** [shadowmage45/SSTULabs#338]
Hiya,

I was installing mods and noticed that the LV-N atomic engine went missing. I found that this mod was causing the issue. I did a clean install of KSP and the LV-N was fine, but then I installed SSTU (version 0.4.31.119) and the LV-N went missing. Crafts that previously had the LV-N were said to have "experimental or invalid parts" and I could not use them even though the engine was displayed in the VAB.

**Comment by shadowmage45** [comment]
Yes, this is intentional;  SSTU replaces the stock NRV with a clusterable version.  Unfortunately the replacement has a different part-name so is incompatible with existing craft.

The next update will see the stock NRV hidden rather than deleted; so existing craft will still work, but the stock engine will not be accessible from the editor or R&D scenes.

**Comment by Mogball** [comment]
Hmm, I thought that might've been the case, but the clusterable NRV runs on liquid hydrogen instead of liquid fuel. Will this be changed in the next update?

**Comment by shadowmage45** [comment]
Apparently I already am just hiding the stock engine; so no change was needed.

No, I will not be changing it to run on LF; they will use LH2.

You are free to remove the 'stock-nrv-hiding-patch' if you want the stock engine back; it can be found at SSTU/Patches/StockParts.cfg -- removing this patch will restore the stock NRV engine (while leaving the SSTU clusterable ones available as well).
