### ISSUE TITLE
Station Core: USI-LS Information and Feedback

### ISSUE THREAD

**Issue by shadowmage45** [shadowmage45/SSTULabs#340]

**Comment by shadowmage45** [comment]
From Domfluff:

Brief thoughts on the DOS modules, and USI-LS. Obviously actual figures here are meaningless until the parts are finalised/balanced, but still worth thinking about.

ST-DOS-LAB (lab)
ST-DOS-STR (storage)
ST-DOS-TKS

These are probably fine without additional USI-LS configs, since the seating will do the trick.

ST-DOS-COM (station core), HAB and FEM would need some thought. COM and HAB will want some bonus to Kerbalmonths, and FEM will provide a multiplier. In Roverdude's notes, these should be derived from the mass. Since much of the point of SSTU is combining parts, it wouldn't be appropriate (or balanced) for the multiplier to be equal to the mass of the entire module - instead this should have a multiplier based on whatever the "payload" mass should be of the module. Probably not more than ton or two for the multiplier (exercise equipment, etc.), but the KM's can be the total mass of the module, more or less.

Aside from fiddling with the exact numbers, I think that all works in a fairly sensible fashion.

In terms of required space for supplies - a Kerbal eats 16.2 supplies a day, so a 90 day mission consumes 1458 supplies, which means that a two person crew noms through about 3000, or about 3 tons. Since that's more-or-less within Progress capabilities, that makes sense to me as a baseline.

I'd be tempted to not include any recyclers in the DOS parts at all (and certainly no processors), but that's also worth thinking about.

*

ST-HAB-A through D are relatively simple to sort, since they'll provide a bonus to Kerbalmonths relative to their mass (whatever their mass ends up being).

The ST-COS-xxx modules are a little harder to grok right now, since they are currently a lot more generic than the DOS modules, and don't easily split into multipliers/non-multipliers. You can make a really good argument that the rotating torus parts (ST-HAB-E through H) will grant multiplicative bonuses, but again deciding how much they should have is awkward here. 

One option for the ST-COS modules might be to treat them as generic, multipurpose modules - they do a little of everything, and therefore supply a small amount of multiplier, additional kerbalmonths and recycling. This would mean that individually they wouldn't be anything special, but if you strapped enough of them together they would sum to something significant.

**Comment by Domfluff** [comment]
Played around with this some more, and a few more things are clear.

I do think an effective 6000 supplies in the TKS and COM modules are correct, since that's 90 days for two crew (16.2 supplies/day) The available seats give sufficient Hab/Home time already, so I think this would be fine.

The problem is that 6000 supplies is six tons, which is significantly more than a Progress can take to the station (around 3 tons). This would imply that the TKS module has a 50% recycler (capacity 3) built in, which I think I'd be happy with. This also means that the TKS and COM modules need a 3000 supply capacity.

The COM module is the core of the MIR station, and also the bulk of the ISS's life support, so this recycler is pretty fundamental. The Russian recyclers don't recycle urine, so this can be less than the 75% that the US recyclers should have. I'm not sure what capacity this recycler should have either, but a three kerbal capacity and 65% might be sufficient as a baseline, and would be a nice intermediate part between the above.

Looking at the ISS, it's notable how there aren't any dedicated "hab" modules in the station (that have actually been launched - there have certainly been plans for such).

The ST-HUB-COS modules should be the provider of recyclers for the ISS and similar, with 75% efficiency. These could have a crew capacity of 3 each, meaning that the ISS could support up to 12 Kerbals in total, if you maxed out it's recyclers.

My test ISS: [http://i.imgur.com/fIZ9ZlJ.jpg](url)

Has no supplies yet, and a hab time of 1 year, 16 days.

Since we know that the longest the ISS has been without supplies is 128 days (round it up to 150 for margins), and we know people can live on there for a year, then that hab time actually looks okay without any Kerbalmonth bonuses to me. The stock Cupola applies a x1.76 multiplier, and that brings you up over the year mark. Any dedicated hab parts (inflatable module) will provide a bonus - the BEAM module (ST-HAB-D) will add a small amount to that.

150 days is 2500 supplies per Kerbal assuming no recycling. Assuming max efficiency in-space recycling (75%), this means that each Kerbal is consuming 25% of that, or 625 supplies.Multiplied by 6 Kerbals, that's 3,750 supplies total on the ISS when fully functional.

Since the ISS has both a COM and TKS module, they will have more than sufficient supply space with just the Russian side of the station. This might imply that there are no supplies stored in the US lab parts, and just a small amount in the docking hubs, with the life support equipment.

I could well see differentiating the US and Russian parts as being single-use and multipurpose. The US parts have the best labs, hab space, etc., but the Russians are more all-in-one in their approach.

I think I'm happy with the idea of the Torus parts supplying multipliers, and (perhaps more importantly) using that as shorthand for how to determine a multiplier's effect. The smallest torus should have a sub-1.0 multiplier (say, x 0.55), and the largest can be something quite silly - I was assuming something like  x0.55, x1.0, x3.0, x5.0, but that may be too low.

I liked the idea of considering the largest torus as either being sufficient for a space hotel when full, or a manned mission to the most distant planet when crewed with four Kerbals. This should also offer additional Kerbalmonths, which means this is almost a do-everything part, but it'll also be huge, expensive and very massive, so that might be fine. A late game part in any case.

**Comment by Domfluff** [comment]
A Mir-like station would have five or six modules. Five modules gives a hab time of 150 days for three crew. Longest stay in orbit was 437 days on the Mir space station, so this will need some bonuses and/or multipliers.

The longest Mir went without resupply was 240 days. Rounding to 300, that's 4,860 supplies per Kerbal. (14,580 for three)

Assuming the 65% recycling (3 kerbals) above provided by the Core module, that's 5103 supplies total - so it would take two Progress launches to fully resupply this Mir. 5000+ supplies could easily be 1000 supplies per module on average - labs having less and the habitation modules having more.

If we assume that the Mir modules weren't just labs, and were a combination of the other parts (-HAB providing bonus Kerbalmonths (e.g., +6 kerbalmonths) and -FEM providing a x1 multiplier) then I think this would get to a sensible level pretty quickly. This would encourage creating a mess of different modules, which is probably important.

**Comment by Domfluff** [comment]
// As noted, this patch currently does not work correctly. The COS hubs are fine, but everything else is running into issues - presumably with how the part switching is defined.

// The US ISS docking hubs consist of the primary Life support equipment for US-style modules.

@PART[SSTU-ST-HUB-COS] 
{
    MODULE
    {
        name = ModuleLifeSupport
    }

```
   RESOURCE
{
    name = Supplies
    amount = 500 // One kerbal for a month before recycling
    maxAmount = 500
}
RESOURCE
{
    name = Mulch
    amount = 0
    maxAmount = 500
}
RESOURCE
{
    name = ReplacementParts
    amount = 500
    maxAmount = 500
}

MODULE
{
    name = ModuleLifeSupportRecycler
    CrewCapacity = 4
    RecyclePercent = .75 //ISS recycles at 75% efficiency
    ConverterName = Life Support
    tag = Life Support
    StartActionName = Start Life Support
    StopActionName = Stop Life Support

    INPUT_RESOURCE
    {
        ResourceName = ElectricCharge
        Ratio = 1
    }
}
MODULE
{
    name = USI_ModuleFieldRepair
}
```

}

// Concept for the DOS parts is that each part offers a unique role, 
// so that a Russian-style deep space vehicle would look a lot like Mir with a propulsion unit.

@PART[SSTU-ST-DOS-COM] 
{
    MODULE
    {
        name = ModuleLifeSupport
    }

```
RESOURCE
{
    name = Supplies
    amount = 1500 // Three kerbals for a month before recycling
    maxAmount = 1500
}
RESOURCE
{
    name = Mulch
    amount = 0
    maxAmount = 1500
}
RESOURCE
{
    name = ReplacementParts
    amount = 500
    maxAmount = 500
}

MODULE
{
    name = ModuleLifeSupportRecycler
    CrewCapacity = 12
    RecyclePercent = .66 //Less efficient than the US modules, but covers more Kerbals
    ConverterName = Life Support
    tag = Life Support
    StartActionName = Start Life Support
    StopActionName = Stop Life Support

    INPUT_RESOURCE
    {
        ResourceName = ElectricCharge
        Ratio = 1
    }
}
MODULE
{
    name = USI_ModuleFieldRepair
}
```

}

@PART[SSTU-ST-DOS-HAB]
{
    MODULE
    {
        name = ModuleLifeSupport
    }

```
RESOURCE
{
    name = ReplacementParts
    amount = 1095
    maxAmount = 1095
}
RESOURCE // 3 Kerbals for nine days = 292 supplies
{
    name = Supplies 
    amount = 292
    maxAmount = 292
}
RESOURCE
{
    name = Mulch
    amount = 0
    maxAmount = 292
}
```

}

```
MODULE
{
    name = ModuleHabitation
    KerbalMonths = 39.75
}

MODULE
{
    name = USI_ModuleFieldRepair
}
```

}

@PART[SSTU-ST-DOS-FEM]
{
    MODULE
    {
        name = ModuleLifeSupport
    }

```
RESOURCE
{
    name = ReplacementParts
    amount = 1095
    maxAmount = 1095
}
RESOURCE // 3 Kerbals for nine days = 292 supplies
{
    name = Supplies 
    amount = 292
    maxAmount = 292
}
RESOURCE
{
    name = Mulch
    amount = 0
    maxAmount = 292
}
```

}

```
MODULE
{
    name = ModuleHabitation
    HabMultiplier = 1 //Completely arbitrary value for testing
}

MODULE
{
    name = USI_ModuleFieldRepair
}
```

}

// LAB and STR parts just need the nine days of supplies for transit, no bonuses or modifiers

@PART[SSTU-ST-DOS-LAB]
{
    MODULE
    {
        name = ModuleLifeSupport
    }

```
RESOURCE
{
    name = ReplacementParts
    amount = 1095
    maxAmount = 1095
}
RESOURCE // 3 Kerbals for nine days = 292 supplies
{
    name = Supplies 
    amount = 292
    maxAmount = 292
}
RESOURCE
{
    name = Mulch
    amount = 0
    maxAmount = 292
}
```

}

```
MODULE
{
    name = USI_ModuleFieldRepair
}
```

}

@PART[SSTU-ST-DOS-STR]
{
    MODULE
    {
        name = ModuleLifeSupport
    }

```
RESOURCE
{
    name = ReplacementParts
    amount = 1095
    maxAmount = 1095
}
RESOURCE // 3 Kerbals for nine days = 292 supplies
{
    name = Supplies 
    amount = 292
    maxAmount = 292
}
RESOURCE
{
    name = Mulch
    amount = 0
    maxAmount = 292
}
```

}

```
MODULE
{
    name = USI_ModuleFieldRepair
}
```

}

// Definitions for VA Pod and TKS module
// Compared to Apollo this is a heavier pod, but with longer duration due to recycling supplies

@PART[SSTU-ST-DOS-TKS]
{
    MODULE
    {
        name = ModuleLifeSupport
    }

```
RESOURCE
{
    name = ReplacementParts
    amount = 820
    maxAmount = 820
}
RESOURCE // 3 Kerbals for nine days = 292 supplies
{
    name = Supplies 
    amount = 292
    maxAmount = 292
}
RESOURCE
{
    name = Mulch
    amount = 0
    maxAmount = 292
}
```

}

```
MODULE
{
    name = ModuleLifeSupportRecycler
    CrewCapacity = 8
    RecyclePercent = .65 //Less efficient than the US modules, but covers more Kerbals
    ConverterName = Life Support
    tag = Life Support
    StartActionName = Start Life Support
    StopActionName = Stop Life Support

    INPUT_RESOURCE
    {
        ResourceName = ElectricCharge
        Ratio = 1
    }
}

MODULE
{
    name = USI_ModuleFieldRepair
}
```

}

@PART[SSTU-SC-D-CM] 
{
    MODULE
    {
        name = ModuleLifeSupport
    }

```
RESOURCE
{
    name = ReplacementParts
    amount = 467
    maxAmount = 467
}
RESOURCE // 3 Kerbals for three days = 146 supplies
{
    name = Supplies 
    amount = 146
    maxAmount = 146
}
RESOURCE
{
    name = Mulch
    amount = 0
    maxAmount = 146
}
```

}

```
MODULE
{
    name = USI_ModuleFieldRepair
}
```

}

// Hab Inflatables should only provide bonus kerbalmonths. 
// Torus parts are providing multipliers - these figures are currently guesswork only

@PART[SSTU-ST-HAB-A]
{
    MODULE
    {
        name = ModuleLifeSupport
    }

```
RESOURCE
{
    name = ReplacementParts
    amount = 950
    maxAmount = 950
}

MODULE
{
    name = ModuleHabitation
    KerbalMonths = 17.5
}
MODULE
{
    name = USI_ModuleFieldRepair
}
```

}

@PART[SSTU-ST-HAB-B]
{
    MODULE
    {
        name = ModuleLifeSupport
    }

```
RESOURCE
{
    name = ReplacementParts
    amount = 2650
    maxAmount = 2650
}

MODULE
{
    name = ModuleHabitation
    KerbalMonths = 87.5
}
MODULE
{
    name = USI_ModuleFieldRepair
}
```

}

@PART[SSTU-ST-HAB-C]
{
    MODULE
    {
        name = ModuleLifeSupport
    }

```
RESOURCE
{
    name = ReplacementParts
    amount = 5345
    maxAmount = 5345
}

MODULE
{
    name = ModuleHabitation
    KerbalMonths = 207.25
}
MODULE
{
    name = USI_ModuleFieldRepair
}
```

}

@PART[SSTU-ST-HAB-D]
{
    MODULE
    {
        name = ModuleLifeSupport
    }

```
RESOURCE
{
    name = ReplacementParts
    amount = 355
    maxAmount = 355
}

MODULE
{
    name = ModuleHabitation
    KerbalMonths = 2.75
}
MODULE
{
    name = USI_ModuleFieldRepair
}
```

}

@PART[SSTU-ST-HAB-E]
{
    MODULE
    {
        name = ModuleLifeSupport
    }

```
RESOURCE
{
    name = ReplacementParts
    amount = 1184
    maxAmount = 1184
}

MODULE
{
    name = ModuleHabitation
    KerbalMonths = 34.2
    HabMultiplier = 0.55 // Completely arbitrary test value
}
MODULE
{
    name = USI_ModuleFieldRepair
}
```

}

@PART[SSTU-ST-HAB-F]
{
    MODULE
    {
        name = ModuleLifeSupport
    }

```
RESOURCE
{
    name = ReplacementParts
    amount = 3400
    maxAmount = 3400
}

MODULE
{
    name = ModuleHabitation
    KerbalMonths = 120
    HabMultiplier = 1.0 // Completely arbitrary test value
}
MODULE
{
    name = USI_ModuleFieldRepair
}
```

}

@PART[SSTU-ST-HAB-G]
{
    MODULE
    {
        name = ModuleLifeSupport
    }

```
RESOURCE
{
    name = ReplacementParts
    amount = 8408
    maxAmount = 8408
}

MODULE
{
    name = ModuleHabitation
    KerbalMonths = 320.4
    HabMultiplier = 3.0 // Completely arbitrary test value
}
MODULE
{
    name = USI_ModuleFieldRepair
}
```

}

@PART[SSTU-ST-HAB-H]
{
    MODULE
    {
        name = ModuleLifeSupport
    }

```
RESOURCE
{
    name = ReplacementParts
    amount = 19416
    maxAmount = 19416
}

MODULE
{
    name = ModuleHabitation
    KerbalMonths = 820.8
    HabMultiplier = 5.0 // Completely arbitrary test value
}
MODULE
{
    name = USI_ModuleFieldRepair
}
```

}

**Comment by shadowmage45** [comment]
Indeed, you cannot just add resources to most SSTU parts; they need the resources added to the VolumeContainer (both as applicable resources, and the default resources for the part updated).

I'll have a basic patch available with the next release that should add USI-LS stuff to most/all of the station parts.  Still working through the overall balance on them, but at least they'll have -something- in place.

**Comment by taterkerman** [comment]
Figured I'd add to this. You have also suggested an "empty space' or "habitable space" as part of the container system that cannot be messed with... though from looking at ISS images (inside), it's rather like an old German WW2 submarine leaving for a patrol (cans stacked on the floor, etc).

RoverDude uses the Lab parts for recyclers, and SSTU is not limited that way.

All the tori should have converters, with at least 70% efficiency. HAB-A1/2 perhaps have no recycler, and COS-S and larger can have one. I think this will play into when the part appear in the tree, and the upgrade functionality can also be useful. Early station parts might have no recycler, or very low efficiency. 

Salyut 6 was occupied for 683 days. It was visited, however, by 36 spacecraft, and had 16 crews. That's under 3 weeks per resupply. If you assume zero resupply with the Soyuz with crews, that leaves 20 resupply missions, and the duration goes to 34 days. I suppose that's a sort of benchmark for setting the base capabilities of the DOS parts. The longest Salyut flights were about 180 days, so the habitation factor should take that into account.

I'd assume the COS parts would be more capable, and appear later in the tree (any that appear earlier can be less capable, then upgrade, I suppose).

The units meant to mimic Bigelows would start at upgraded COS level (and appear later), and would have recyclers, etc.

Tori should have, well, everything.

Habitation gives the HH a 12.5 kerbal-month habitation bonus, and it's pretty cramped. Assuming the current crew levels, the COS-S is the same size, but for 2 crew, so the habitation should be better than the HH's 3.135 mo/seat. That will benchmark the SSTU parts as far more habitable.

That's actually another weird aspect of the base habitation in USILS. It's a month (30 kerbin days) per SEAT. That sort of requires that everything be scaled to that sort of volume per seat. The HH gets a bonus on top of that, making the total 4 months per seat---and it is tiny. Assuming the same bonus as HH for the CFG-A, we have 6 kerbal-mo + 18.75 kerbal-mo (bonus) = 24.74 kerbal months (1.74 years). That's with no other modifiers. Where it gets odd, though, is parts with a very high mass to crew ratio. The -D gets 24 months base habitation, and with the same 3.125 months per crew bonus as HH, that's still only a base of 4.125 months per kerbal. Seems like a multiplier or a huge bonus is needed.

The hab multiplier is a huge thing. A single cupola is a 1.76X multiplier on habitation (part mass). Using Roverdude's suggestion of part mass... the tori start looking pretty good if they get to be multiplier parts (the -D with a 158X multiplier). Clearly that gets crazy pretty fast. The bonuses might be the easier route, though I think the tori should give a multiplier since gravity is huge from a health/quality of life standpoint (the ability to use a real toilet alone is better than a cupola). Maybe a benchmark for a habitation multiplier could be something like k*1+(effective gravity).

**Comment by shadowmage45** [comment]
All station core parts have had initial life-support balancing added to them.  

* All habitable parts include ~30 k-days worth of supplies for their maximum crew capacity.  For the largest inflatable parts this is quite a bit of supply storage.
* All recyclers, where included, are currently 90%.  In the future this may use the upgrade system and start at a lower value (40-60%) and unlock up to 90%.
* All modules currently use 'rated crew' * 3 for the 'BaseKerbalMonths'  (some modules may be rated for less than their maximum crew, see below)
#### DOS
* DOS modules are rated for generally 2 crew, 3 in the FEM and HAB parts (6mo and 9mo)
* DOS modules have varying multipliers, 
  * 0 for COM, LAB, PWR, TKS, 
  * 1 for HAB
  * 2 for FEM
* DOS modules that include recyclers are the FEM and HAB, at crew capacity 4, and TKS at crew capacity 2 (90%)
#### COS
* COS modules are all rated for their stated crew capacity (1,2,3,5)
* COS-HAB-3 and COS-HAB-5 both have a hab multiplier of 1
* COS-HAB modules all contain recyclers for their rated crew capacity (90%)
* COS-LAB modules all contain recyclers for double their rated crew capacity  (90%)
#### HAB
* HAB modules are all rated for their inflated crew capacity
* HAB-A modules have a multiplier 1
* HAB-B and HAB-C modules have a multiplier of 2
* HAB modules do not contain any recyclers (may add in the future)
#### CFG
* HAB modules are all rated for their inflated crew capacity
* CFG-A has a multiplier of 1
* CFG-B has a multiplier of 2
* CFG-C and CFG-D have a multiplier of 3
* CFG modules do not contain any recyclers (may add in the future)


Will leave ticket open for awhile longer for further discussion on balance changes.

**Comment by taterkerman** [comment]
I'd think the CFGs would have "all the things," lol.
