### ISSUE TITLE
Enabling/disabling staging on certain parts not working

### ISSUE THREAD

**Issue by Duskii** [shadowmage45/SSTULabs#353]
Hi, it's Duski from the KSP forums.

I've noticed an issue with enabling and disabling stages. The Interstage Petal Adapter is a victim of this bug. Example: If I disable the bottom payload to decouple through staging, When I get to the Petal Adapter stage, it still decouples it anyway.

**Comment by Duskii** [comment]
Disregard, has been already discussed.

**Comment by shadowmage45** [comment]
Hmm...  
Going to actually re-open this one for now, because it sounds like there is an actual bug with it.

While the staging icon won't update (stock problem) the actual -functions- of the staging should update with the UI toggles. 

Will attempt to take another look at this one for the 1.2 port/update.  Could be some config stuff that is setup wrong, or some cross-module interaction messing things up.

**Comment by Duskii** [comment]
Ok,
While I was having a little stroll through the big repository, I found the other thread mentioning this, and this bug is also with other parts just to clarify. Once I get home, I'll have a look on other parts too.

**Comment by shadowmage45** [comment]
Interestingly enough -all- custom staging setup is broken in 1.2 -- none of the buttons even show up in the editor.

Will def. be taking another look at this as the 1.2-pre-releases progress.
