### ISSUE TITLE
Separate Folders

### ISSUE THREAD

**Issue by dtoxic47** [shadowmage45/SSTULabs#387]
Separate folders so it is easy to delete unwanted parts, and so that users can run it on low end machines

**Comment by taterkerman** [comment]
This is not really an "issue." Directory structure is what shadowmage thinks it should be to optimize his workflow and ability to find/modify work in the future. FWIW, I am running on a 6 year old machine, and SSTU runs fine.

**Comment by dtoxic47** [comment]
it's more for the "delete unwanted parts" the old machine is just an added bonus i guess (personally don't have any issues with the mod) i just use 80+ mod's and delete parts that i don't use (no need to get them loaded in memory right? :) )

anyway do take it into consideration would help a lot.

**Comment by shadowmage45** [comment]
It has already been considered and cannot be done due to limitations on how KSP manages sharing of textures and models.

Basically the problem comes down to -- KSP expects all textures for a model to be located in the same folder as that model.  Some of my models use textures from multiple other models (e.g. anything with engines usually has a base texture, and shares the texture from the engine).

The only way to get these to load with KSP would be to duplicate the textures into multiple folders, resulting in even larger distribution size, and an absolute waste of space due to duplicate textures.  KSP technically does allow to specify a replacement texture for a model in the MODEL node, but it relies on the 'texture-to-be-replaced' already existing and being in the same folder, so I would have to add a bunch of proxy/dummy/empty/placeholder textures all over, leading to a very confusing setup (as there would be multiple textures with the same name; some of them real, some of them fake).


This doesn't stop you from removing unwanted assets, you merely need to know exactly what you want to keep / what you want to remove.

**Comment by dtoxic47** [comment]
i already tried, as for the models it;s easy to see witch ones to keep, but textures are a bit harder, cant seem to find the right combination,anyway no big deal though id suggest it but it seems it;s more work than reward so it does not matter :)
