### ISSUE TITLE
Proc. Interstage decoupler GUI options

### ISSUE THREAD

**Issue by Jimbodiah** [shadowmage45/SSTULabs#396]
Some GUI options, like the top and bottom decoupling, for the Interstage decoupler are only visible when Advanced Tweakables are enabled. 
![after](https://cloud.githubusercontent.com/assets/16107012/21600188/8f81fa80-d178-11e6-98a3-31d1d122c124.jpg)
![before](https://cloud.githubusercontent.com/assets/16107012/21600187/8f805cf2-d178-11e6-8048-3f52e215f592.jpg)

**Comment by shadowmage45** [comment]
Stock options = stock options.

I'll see if the 'advanced tweakables' setting on those UI options is adjustable through config.  Don't think that it is, but will take a look at it.  The problem is that it is all part of the stock ModuleDecouple, which I can neither edit nor extend (last time I tried extending it there were all sort of problems with other mods that are hard-coded to only accept the stock decoupler module; e.g. mechjeb, ker, and kjr).  

The only option is if the stock code allows for removing those from 'advanced tweakables' through a config setting on a per-part basis;  the default 'advanced tweakable' state is defined through the source-code of each ui control for each module, and generally not exposed to config-file-based configuration.

**Comment by blowfishpro** [comment]
Is enabling advanced tweakables really that much trouble?  I have trouble imagining a decent moderately-modded game without them.

**Comment by Jimbodiah** [comment]
No, that is not the point. People that do not enable it will just not see these options and wonder why not (like I did after a fresh install).

**Comment by shadowmage45** [comment]
@SixDasher you do have a valid point, and I can absolutely see where you are coming from -- the decoupler staging features are necessary toggles to the proper configuration and function of the ISDC part.

The problem in this case is that stock code has decided that decoupler staging features are an 'advanced' feature, and I'm **unsure** if I can even alter it.  (Literally it is hard-coded into the stock ModuleDecouple UI field definitions and might not be fixable even with custom plugin code)

I'll look into it during my next updating pass, but it may well come down to 'need to open a stock feedback/bug-report to have them open the 'advanced' setting for modules UI functions to configuration through .cfg files'.

**Comment by Jimbodiah** [comment]
np for me, just wanted to mention it.

**Comment by shadowmage45** [comment]
Ho, hum... fixed in dev repo, will be available with the next update.

````
Events[nameof(ToggleStaging)].advancedTweakable = false;
decoupler.Events[nameof(ToggleStaging)].advancedTweakable = false;
````
