### ISSUE TITLE
LC2 LC3 landers - bottom tube doesn't reach next item

### ISSUE THREAD

**Issue by riocrokite** [shadowmage45/SSTULabs#4]
bottom 'tubes' in lc2 lc3 lander cans don't reach next object that is attached to them

http://i.imgur.com/p8I2OPY.png
http://i.imgur.com/w42xSbG.png

**Comment by shadowmage45** [comment]
Completely Intentional.

There are two bottom attach nodes on the lander cans.  The lower one is for fuel tanks (the external ring, which you have parts mounted on), the slightly higher one (the internal cylinder) is for the ascent engines to be mounted.  The currently included decoupler on the pods decouples the lower node/outer ring (this decoupler module will likely be removed before public release; intended to be replaced by the physics-less procedural decoupler part).

The nodes are quite close together though, and a bit fiddly to get parts to snap properly onto both of them.  Am considering turning one of the nodes into an optional/toggle-able node to clean up some of the fiddly-ness of them.

**Comment by shadowmage45** [comment]
Have removed decoupler module from pods, and added the second (lower/fuel tank) node as an optional toggle-able node (right click on the part and click 'add node').  Parts will now by default attach to the engine-attach node; things intended for the outer ring/fuel tank node will need to have the node manually added prior to be attached.

Should resolve issues with wonky decoupler staging stuff, and add a bit cleaner separation between the engine and outer node.

Will have this in place for the next test release.

**Comment by shadowmage45** [comment]
Unfortunately the selectable nodes module did not seem to want to work on these parts for some reason (although, it works fine on engines? Might be something to do with the pod being the root part).  

Will be releasing without the module for now, and add it in (if needed) when I have time to find out what was going on (will be prior to public release).
