### ISSUE TITLE
Docking port integral chutes lack texture (path change in texture made it point to wrong directory)

### ISSUE THREAD

**Issue by taterkerman** [shadowmage45/SSTULabs#444]
SC-GEN-DP-0P and 1P have no texture since the path is:

texture = SSTU/SharedAssets/SSTU-GEN-PAR-ORANGE2-DIFF

should be

texture = SSTU/Assets/SSTU-GEN-PAR-ORANGE2-DIFF

**Comment by taterkerman** [comment]
Odd thing. Fixing the texture was trivial, but I have had issues with the small chute (I haven't tested the larger) actually deploying. I did pad tests launching a TRAILS Gemini with a solid, then testing the SSTYU chute. Works fine.

I then flew the craft to orbit, and the chute never deploys, the capsule drops straight into the drink at terminal velocity. I have tested this now a few times.

Looking at the cfg files for SC-GEN-DP-0P vs SC-B-CM, there are a number of differences.

The latter has a drogue chute, while the docking port only has the mains. Could it be that the allowable deploy speed for the mains is below the velocity possible for the capsule under normal reentry conditions minus a drogue? Ie, the drogue slows the capsule to allow the mains on the Apollo, but on another capsule, since the docking port has no drogue, it never slows enough to allow deployment?

EDIT: OK, a quick test shows this to be the case. If I add drogues to a suborbital test vehicle, they slow it enough to allow the docking port chute to deploy. Perhaps the small docking port should be instead given the chute package from the Soyuz, and the larger port could be given drogues as well as mains?

**Comment by shadowmage45** [comment]
Thanks for the report on the texture path.  Been so long since I had used that feature on those parts, forgot it even existed.  Simple enough to fix up though.

As to the chutes not activating -- could be a case of either the craft has too much mass for its drag (too high of a BC), and thus doesn't slow down enough -or- could be that the chutes are set to not activate until to low of a speed.

What is the terminal velocity that you are achieving with your craft prior to chute deployment?  I believe I had the chutes set for something like ~200m/s for their 'safe to deploy' speed.

**Comment by taterkerman** [comment]
I'll have to pay attention next time I can test for you. I know that slapping a couple stock drogues on there slowed it such that it deployed fine. For the SSTU capsules, the drogues deploy and drop it to under 200, and the docking ports don't have drogues at all.
