### ISSUE TITLE
USI Kontainers

### ISSUE THREAD

**Issue by DocRockwell** [shadowmage45/SSTULabs#448]
In the optional patches for USI kontainers, the model.cfg calls for MKS (modular kolonization systems) instead of Kontainers, causing the part to have missing models. If MKS is installed, the model works, but the part is still bugged, as the tank has no contents (ie fuel)  and can only have its diameter and texture switched.

**Comment by shadowmage45** [comment]
Thanks for the report.  Will look into getting the optional patch set developed a bit further for the next release, and at least get the tanks fixed up.

**Comment by lynwoodm** [comment]
ModelData-Kontainers.cfg has the SSTU_MODEL:NEEDS[MKS]. Shouldn't this be 

`SSTU_MODEL:NEEDS[Kontainers]`

**Comment by shadowmage45** [comment]
Possibly now, yes.  But not when I first put the patches together (Kontainers were bundled as part of MKS at the time, which was actually called MKS... none of that current UKS stuff).  I'm sure there are a few other changes that the patches need to account for the updated USI mods layout as well.

Yes, it has been that long since I've been able to work on them, probably about 5-6 months (I think I was working on them during the 1.1.3->1.2 KSP updates, or shortly after 1.2 was released).

A good majority of the UKS/MKS/USI patches will likely be reworked for the updated USI mod layout, and for my intended use of the mod setup (e.g. removing GroundConstruction as a dependency, reworking EL as the in-situ construction mod of choice).

**Comment by lynwoodm** [comment]
It seems that just changing the NEEDS doesn't do squat. RoverDude put the Kontainers as part of the USI Core mod, which includes the reactors. Even when KSC-AVC goes through the mods, it doesn't recognize the Kontainers mod as a separate mod. It just shows USI Core as the mod. 

With that said, I don't see why just re-naming the NEEDS to Kontainers doesn't fix this?

**Comment by shadowmage45** [comment]
Additional note:  Need to add NTO/Aerozine to the stock ISRU system, to allow for fuel refinement...

**Comment by shadowmage45** [comment]
Huh, apparently there simply is not a viable NEEDS block for the Kontainers bit of USI mods after the recent changes.  Wonderful.

At this point I'm pretty much done dealing with USI mod integration; RD keeps changing things around, and the mods are not what I fell in love with in the beginning (too many new mechanics that only add tedium).
