### ISSUE TITLE
1.25m decoupler one node earlier

### ISSUE THREAD

**Issue by Jimbodiah** [shadowmage45/SSTULabs#467]
Is it OK to change the starting node for the 1.25m proc. decoupler to basicRocketry (one node earlier)? This would enable using all SSTU parts instead of the fugly stock decoupler ;)

**Comment by shadowmage45** [comment]
I'll have to give it some thought.

The original intent behind having the decoupler unlock later in the tree is because a procedural part is a powerful tool, I wanted there to be some sense of 'accomplishment' in unlocking it and finally being able to use it.

On the other hand, with some of the other semi-recent changes to SSTU part tech-tree placement, and having adjustable tanks quite early in career mode, I can see the use (and need) for an adjustable decoupler that unlocks and advances with the tanks.  That would place the decoupler at either the 2nd or 3rd tier, unlocking at the same time as the MFT-A fuel tank, with diameter unlocks moving to the same tiers as the corresponding tank diameter unlocks.

**Comment by taterkerman** [comment]
The stock tree is so awful, it's hard to justify using it as a model, LOL. We'll always have the accomplishment of figuring out ladders, right? :-D

**Comment by Jimbodiah** [comment]
@taterkerman  haha, yeah, I always wondered why those were so far up :)

@shadowmage45  That was what I was after, as we have a 1.25m stock part but not the SSTU one. I get holding back the interstage decoupler for 1-2 nodes later than the normal PDC.

**Comment by SixDasher** [comment]
I also notice the 2.5m decoupler is in the same level as the 3.125m tanks, cq too far up the tree by one node.  3.75m is at the same level as the tanks. Should I PR this?

**Comment by shadowmage45** [comment]
Looks like there are a few other decoupler/probe core related unlocks that need to be adjusted now that I've removed the stock-tech-tree adjustments from SSTU.  Will look into doing a full rebalance pass on the tech tree placement for those parts for the next release, at least making sure that the unlocks for a given diameter unlock on the same tier as the fuel tanks (possibly even the same node, and/or using the same unlock/upgrade parts).

**Comment by Jimbodiah** [comment]
![bt_3_excel](https://user-images.githubusercontent.com/16107012/27003500-0ae84b92-4df8-11e7-8887-21f4a2a957d0.jpg)

**Comment by Jimbodiah** [comment]
BTW: I've already changed the cfg files on my own version. Do you want me to PR them, maybe save you some work?

I made the same number of upgrades for the PDC parts as with the tanks, so changed from D1-D4 to D1-D6 and added the corresponding techtree  names to the new upgrades for PDCs (PDC and ISDC).

**Comment by shadowmage45** [comment]
PR's merged, fixes should be available with the next release.

Thanks for the work @SixDasher :)

**Comment by Jimbodiah** [comment]
No problem!

Wish I could change my name here to match my forum name though.
