### ISSUE TITLE
Undocking COS/DOS issue is back?

### ISSUE THREAD

**Issue by Jimbodiah** [shadowmage45/SSTULabs#475]
I just had a DOS lab and a COS module which would not undock on it's port. There was an option to undock (decouple) the bottom port, but despite there not being a bottom port, it did seperate from the ship it was permanently attached to.

I've added the logs, but it's a game with other mods running.

**Comment by Jimbodiah** [comment]
http://jimbodiah.com/ksp/sstu/sstu_ports.zip

**Comment by shadowmage45** [comment]
Yeah, the old ticket is still open/around somewhere.

I've never been able to reliably duplicate the issue.  Logs only go so far, especially when they don't actually say anything (no errors/etc listed).  Thanks for including them though, that is always the first step :)

Likely what I'll need to diagnose and fix the problem is a stock/vanilla save-game file from right before the problem occurs, along with a save-game file from right after the problem occurs.  Hard to do though, as it would require saving prior to every docking, and then testing undocking immediately after docked.  Could even be that the problem doesn't manifest that quickly, and requires a game load/reload inbetween the dock and undock events.

Were you problems with the HUB parts, or the regular DOS/COS modules with integrated/selectable ports?

**Comment by Jimbodiah** [comment]
You changed something back then to force the code to show as docked/undocked and that worked without issues. It may have returned in 1.3, but never checked undocking on the previous .135 build to be sure it is new or already present in the previous build.

**Comment by shadowmage45** [comment]
Referencing #382 for relevant information, as I believe the problems are the same (or at least related).
