### ISSUE TITLE
Q: MFT body variant

### ISSUE THREAD

**Issue by Jimbodiah** [shadowmage45/SSTULabs#535]
I made a copy of the MFT-A, removed the VolumeContainer but kept the rest. Now I can only choose between the kerolox and hydrolox body variants, not the the cryo or the cradle thingy version. Is this linked to having SSTUVolumeContainer?

**Comment by shadowmage45** [comment]
No, it is caused by those two body variants being added through an MM patch that explicitly targets the MFT-A part.  If you duplicate the MFT-C/CF patch files, and retarget them to your new part, it should all work.

Edit:  Link to one of the patch files:  https://github.com/shadowmage45/SSTULabs/blob/dev/GameData/SSTU/Parts/ShipCore/Tanks/SC-MFT-C-TankPatch.cfg

**Comment by Jimbodiah** [comment]
AAAah... okay, thanks!!!!

edit: just added them...   Just a question, is there a reason it's not integrated into the MFT-A file? (ignorance is bliss).

**Comment by shadowmage45** [comment]
Its not integrated as I was sick of writing 1/2-mile long config files (and scrolling through pages of configs), and found it easier to read if I kept it in a separate file as a patch.

Could it be integrated -- yes.  Should it be integrated -- sure, probably wouldn't hurt now.

**Comment by Jimbodiah** [comment]
:)  I thought as much :)

**Comment by shadowmage45** [comment]
If you wanted to throw together a PR that merged that stuff in, I would likely accept/merge it :)

**Comment by Jimbodiah** [comment]
Will do! ;)
