### ISSUE TITLE
Station core mass increase

### ISSUE THREAD

**Issue by Nightside101010** [shadowmage45/SSTULabs#558]
Mentioned this over in the thread, 

For good game balance, and to require sufficiently large rockets, station core parts should be in the 10-20 ton range (COS & DOS modules that is).

**Comment by taterkerman** [comment]
They might be able to be slightly more massive, but 20k is more than they mass in RL. It really depends on scaled mass at kerbal scale.

Being overly concerned with that for the stock, mini system is a can of worms, frankly (IMO), since there are so many factors that don't scale well.

**Comment by shadowmage45** [comment]
I'm using the same balance for station parts' mass that I'm using for everything else -- square scaling; e.g. 0.64 * 0.64 = 0.4096 final scale factor, or 40.96%.

Zvezda = ‎20,320 kg * 0.4096 = ‎~8323kg (full)
ST-DOS-COM = 4950kg + fuel + solar panels + docking ports = ~8300kg = 40.84%

I would say they are balanced fine where they are at.  I don't think it should require a replica rocket to launch stuff in the stock solar system; and the stock part balancing would agree with that.  This suggestion would seem to be much more applicable if it were used with a solar-system rescale; 2.5x, 6.4x, etc (and a corresponding rescale to the part model itself).

I'm pretty sure you can build equivalent functional stations using the stock parts, and often come in with even lower mass.  I've intentionally left them slightly 'heavy' compared to the stock parts / stations, because, yes, they should be a bit difficult to get into orbit.  But they shouldn't require some ridiculous asparagus staged monster to launch them at the point they become available (~2.5m nodes).

|part|mass|propellant|crew|
|----|----|----|----|
Science lab|3.5|0|2|
mk1 lander can|0.6|0|1
FL-R25 RCS Fuel Tankx2|2.3|2.0|
engine|0.09|0||
solar|0.3|0||
battery-4k|0.2|0||
antenna|0.1|0|0|
dock-x2|0.1|||
rcs-x2|0.1|||
**TOTAL**|7.29|2|3|
Delta-V|~1000|||
ISP|315|||

The example stock-station above would have higher DV, full science lab, better solar panels, and still come in at lower mass.

**Comment by MikeOnTea** [comment]
I agree with the stock-like scaled balance. If you want the game to require larger rockets, you need to scale your universe, 2.5x is supposed to yield more realistic rocket sizes with stock-balanced parts, i plan to try that scale together with RSS myself some time.

**Comment by taterkerman** [comment]
There have been mods like a 3.2x rescale, and one I played called 365 (3.2x planets, 6.4X distances, 24 hour days, 365 day years.

Stock parts work just fine.

**Comment by MikeOnTea** [comment]
That's what i was trying to say, stock parts are balanced to be "easy-mode" in a stock universe, if you want more of a challenge, you need to use such scale mods, i guess.

**Comment by Nightside101010** [comment]
Yeah, I live in 3.2x now and its hard to go back. I suspect I'm a RO player in denial. Glad to hear the reasoning behind the mass and thanks for the discussion!
