### ISSUE TITLE
Flame/exhaust animation of SRB-U nozzles and the SRB-A-G nozzle starts too far up/clips the nozzle

### ISSUE THREAD

**Issue by MikeOnTea** [shadowmage45/SSTULabs#569]
The flame/exhaust animation of SRB-U nozzles and (to a lesser extent) the SRB-A-G nozzle starts too far up/clips the nozzle. All SRB-U-nozzles are affected. (I use realplume)
I'm not sure about how the SRB-A-G nozzle can be handled, that would probably need 4 separate fire/exhaust animations to look perfect.

![srb-u](https://user-images.githubusercontent.com/11480934/30954861-0c30ed2a-a432-11e7-9c54-ddbda8ad3093.png)

![srbs](https://user-images.githubusercontent.com/11480934/30954985-64a018d2-a432-11e7-9334-2e8b39234ed4.png)

**Comment by shadowmage45** [comment]
Interesting, will see what I can do about it.  No guarantees though as the stock effects are... limited... as to what can be adjusted (is why RealPlumes is highly recommended; those I can actually adjust/rescale/etc).  

The SRB-U config was copied/cloned from the SRB-A, so in theory, they should use the exact same effects setup (size, position, etc).

Though if it is a transform positioning error, then it probably effects the realplume setup as well.

**Comment by MikeOnTea** [comment]
I do use realplume. :)

**Comment by shadowmage45** [comment]
Even more interesting -- the RP patch for the SRB-A might be broken then, as that looks like the stock effects on both the -A and -U models.

If you zoom out in the screenshot posted above with both -A and -U nozzles, are there different plumes used between the two?

(already known that the SRB-U lacks RealPlume configs, which might explain part of why the effects look so off)

One change / addition that I could make, that would help with both stock and RP effects, is to add a per-nozzle-model config setting for 'position' -- so that the effects might be positioned correctly even for 'long' nozzles

**Comment by MikeOnTea** [comment]
![srb_plumes](https://user-images.githubusercontent.com/11480934/30982043-93eda056-a486-11e7-9f37-10c06d38a75c.png)
Seems like the SRB-As use realplume while the SRB-Us don't?

**Comment by shadowmage45** [comment]
Thanks for the confirmation :)

Yeah, looks like the majority of this issue is simply that the SRB-U parts don't have RealPlume configs yet (already fixed in dev).

the stock effects... still not much I can do about those, but I'll take a stab at it this evening if I have time (might be able to adjust the position a bit... but they still lack any sort of scale control).

**Comment by shadowmage45** [comment]
Fixed up the real-plume effects -- was some additional problems with patches as RealPlume was not removing the existing effects properly (as the part also includes ModuleRCSFX).

![screenshot1](https://user-images.githubusercontent.com/1503399/30994865-c38ef5a2-a473-11e7-9f40-1f845574beb2.png)
