### ISSUE TITLE
Fairing weight per area should be reduced

### ISSUE THREAD

**Issue by MikeOnTea** [shadowmage45/SSTULabs#572]
Stock fairings are roughly half the weight per area, thus sstu's fairings should be reduced in weight accordingly.
Real life fairings are even lighter according to [braeunig.us](http://www.braeunig.us/space/specs/atlas.htm).
I've thus tried setting UnitAreaMass = 0.015, this seems to result in fairings slightly lighter than stock fairings if used with a same size diameter base. Might be ok though as stock fairings allow to use smaller bases for a given cargo and save even more weight that way.

**Comment by shadowmage45** [comment]
Thanks for the report, and bigger thanks for doing some testing and offering a suggested value.  Almost takes all of the work out of it :)

Being 'slightly lighter than stock' would be okay as long as it is -very slightly- (a few %, <10%).  Will take a look at your suggested mass and see where to go from there.

Would expect this change to be merged in for the next release.

----

How do the petal adatpers and ISDC compare vs. the stock-procedural-fairing based parts?  (Might as well balance them all at the same time)

**Comment by MikeOnTea** [comment]
Sorry, should have provided the numbers. I very roughly recreated the bigger Atlas 1 fairing from the docs which weights about 2t in real life. Fairing base diameter is 3.75m, payload is a 3.75m fuel tank with 3x length. With the unitAreaMass above, the results are as follows:

| |Weight without base|Weight with base|
|-|---------------------:|------------------:|
|Stock|2665kg|3140kg|
|SSTU|2555kg|2766kg|
|SSTU ISDC|~~2170kg||
|SSTU IPA|~2766kg||

The obvious difference is a heavier stock base (also looks heavier though, a solid heavy base, while SSTU has the mesh base, so that kind of matches up with the model).
So, disregarding the base, we get a 4.3% difference.

However, smaller stock fairings have less per area weight, the 2.5m fairing, which can also be used to cover the above test payload, comes in at 2170kg without the base.

Now i've done an additional test with 1.25m diameter fairings and a 1.25m 3x tank as payload, and here the stock fairings are actually still lighter:

| |Weight without base|Weight with base|
|-|---------------------:|------------------:|
|Stock|206kg|281kg|
|SSTU|299kg|307kg|
|SSTU ISDC|~219kg||
|SSTU IPA|~237kg||

So, to completely match stock balance, the weight per area should also be somewhat influenced by the fairing base diameter. Not sure if you want to implement that, but until something like that is done, i guess a weight per area value around the one i proposed is a workable interim solution.

Edit: I've tried to created ISDCs/IPAs which envelop the payloads, and noted their weights (without solid fuel) aswell. The ISDC value for the 3.75m tank is a bit of an estimation as i couldn't enlarge it enough.

**Comment by shadowmage45** [comment]
Overall the values that you've posted seem reasonable to me.  I'll see about making the proposed change in the fairing config files and do a bit of further in-game testing during my current play-testing session.

I think that the difference in the mass of the base makes perfect sense considering the actual models in use.  The SSTU base likely would have far less mass than the giant thick plate of whatever that the stock fairings use for a base.

Will be tough to match the stock setup/scaling exactly on the stock-based fairings because, as you point out, the stock parts alter the 'mass per area' on a per-part basis (and there is only a single part in the SSTU setup). (I could potentially do something about it -- **if** the stock module allows run-time editing of that field **and** if it uses some sort of sane scaling scheme that could be put into an algorithm)

On the SSTU-based procedural fairing parts -- those are a whole nother subject as far as actual balancing them is concerned.  They don't use 'area' for determining the mass of the fairing, but rather the actual 3d volume of the fairing (as a fairing has height, width, -and- depth/thickness) (where the 'thickness' does not increase with base diameter...or does it?  idk/remember).  But from the values you posted above, they already sit about where they should as compared to the closest stock parts.

**Comment by MikeOnTea** [comment]
Did another test with 2.5m diameter fairings and a 2.5m 1.5x length tank as payload:

| |Weight without base|Weight with base|
|-|---------------------:|------------------:|
|Stock|525kg|700kg|
|SSTU|717kg|780kg|

So, apart from 3.75m fairings, even the UnitAreaMass of 0.015 is a little on the heavy side. If you want to test a bit further in your current play test, i suggest to maybe try a slightly smaller value, maybe something around 0.013-0.0135, but that would just be fine tuning.
