### ISSUE TITLE
SSTU/Ferram conflict, KSP 1.30

### ISSUE THREAD

**Issue by vossiewulf** [shadowmage45/SSTULabs#585]
Seeing these in logs where I am crashing entering or leaving the VAB.

`NullReferenceException: Object reference not set to an instance of an object
  at FerramAerospaceResearch.FARPartGeometry.GeometryPartModule.RebuildAllMeshData () [0x00000] in <filename unknown>:0 
  at FerramAerospaceResearch.FARPartGeometry.GeometryPartModule.GeometryPartModuleRebuildMeshData () [0x00000] in <filename unknown>:0 
UnityEngine.Component:SendMessage(String, Object, SendMessageOptions)
UnityEngine.Component:SendMessage(String)
SSTUTools.SSTUModInterop:onPartGeometryUpdate(Part, Boolean)
SSTUTools.SSTUModularFuelTank:updateModels()
SSTUTools.SSTUModularFuelTank:initialize()
SSTUTools.SSTUModularFuelTank:OnLoad(ConfigNode)
PartModule:Load(ConfigNode)
Part:LoadModule(ConfigNode, Int32&)
ShipConstruct:LoadShip(ConfigNode)
ShipConstruction:LoadShip(String)
FlightDriver:Start()
 
(Filename:  Line: -1)`

**Comment by shadowmage45** [comment]
The problem comes down to Unity not deleting objects when told to delete them -- it waits until the next frame.  Sadly if anything comes along and tries to reference those objects prior to them actually being deleted... it causes things to explode (the real solution is for Unity actually delete things when told to).

Have added in a delay to the FAR update callback to make sure the part is initialized and Unity has deleted any meshes/objects marked for deletion.  This should give FAR a 'clean'

(using the same delay that is used for drag-cube updates; meaning the FAR rebuild will be done in the first FixedUpdate after the geometry is updated).

Sadly I have no ability to test this fix (I don't use FAR), and it will only be available for 1.3.1 (the last release was the last 1.3.0 release).  Should be available with the next release (likely this weekend).

**Comment by blowfishpro** [comment]
> The problem comes down to Unity not deleting objects when told to delete them -- it waits until the next frame

Is this true even when using `DestroyImmediate` (as opposed to `Destroy`)?

**Comment by shadowmage45** [comment]
````DestroyImmediate()```` does what it says on the tin, but there can be side effects depending on precisely -when- it is called.  It can cause problems when called from event-handlers and on the UI thread (or anywhere but the main thread).  Hard to track down, mind bendingly strange and inconsistent problems.

It could be a potential solution, but in this case I've simply delayed the far-geometry updates until the next FixedUpdate.  As a bonus each part will only call the voxel update at most once per frame now, rather than potentially many times from editor-modified events.  Seems to be working so far, no null-ref spamming in the editor or flight scenes in simple tests, and FAR appears to be voxelizing things appropriately (according to the log).

**Comment by vossiewulf** [comment]
Sorry I missed this, haven't been looking at my Gmail very much. Thanks for
the fix, I am still waiting on a few more mods to move into 1.31 before I
make the move. And I've been trying to get into MAX to work more on the
part I suggested, but the problem is I just recently started a second
career with these cool SSTU and BDB and Contares mods, and I'm having too
much fun actually playing. Last night did first Ceti landing, and it was
less of a landing and more of an invasion - 4 two-man landers stacked on
top of each other, each with 2200Dv, dropped into three different orbits,
hit all five biomes plus a four-location "run these tests at these
locations" exceptional contract. I haven't landed the last three but I
should end up around 4k science for the trip :)
