### ISSUE TITLE
SSTUSolarPanelDeployable retract jerking

### ISSUE THREAD

**Issue by anxcon** [shadowmage45/SSTULabs#59]
every mod with solar panels has a common issue of once you deploy a solar panel > transforms rotate it around a bit for sun > when you hit retract it (appears) to reset transforms to 0 (where they were moment panel extended) causing a sudden jerk in the craft and retract animation starts same time

what about on retract, manually transform it back to position over time, only then start retract animation

**Comment by shadowmage45** [comment]
The problem is in the coding complexity.  It is certainly doable, but requires a ton of additional code to handle the lerp back to neutral prior to restarting the retract animation.  

So mostly it comes down to a tradeoff of how many hours to implement the feature vs. how much it impacts gameplay.  

As this would take several hours to implement, and has zero impact on gameplay, it is very low priority.  Will leave this ticket open though, as it is a bit of 'polish' that would be nice to have.

**Comment by anxcon** [comment]
figured i should add this to be thorough

i wouldn't say zero impact on gameplay, though it depends on the depth you consider - with the current existing parts in SSTU yes minimal/zero impact due to size of the panels. if future plans add any larger sized and/or multi axis deployable panels, the issue becomes more clear, and even damaging to vessels as the jerk does move/rotate the vessel, which can cause breaking by joints or in atmosphere wind breakage - the more movement + more size adds more force - the largest panel in chopshop part pack for example (using stock solar module, same issue) can be broken on launchpad due to it

but agreed closer to polish

**Comment by shadowmage45** [comment]
Actually, none of those are issues with my solar panels.  They do not have any colliders in the panels, and thus suffer from none of those issues (intentional to not have colliders, JUST to not have those issues).  They imply no torque to the vessel, nor any force of any kind, and will not regardless of how big the panels are. 

As yes, stock panels can tear themselves or your vessel apart; neither of which is acceptable.
