### ISSUE TITLE
MHS at fixed 0.625 steps

### ISSUE THREAD

**Issue by Jimbodiah** [shadowmage45/SSTULabs#597]
The heatshield can only be set at 0.625m increments. The slider on other parts (MFT, PDC, PPC etc) allows fine adjustments within that 0.625m step (like 1.50m).

**Comment by shadowmage45** [comment]
Interesting -- must be a bug (typo) in the UI setup, or possibly incomplete code that is not setting the slider/increments properly.

Should be simple enough to fix up now that I'm aware of it.  Thanks for the report :)

**Comment by Jimbodiah** [comment]
I was also going to add another issue regarding the the heatshield sticking out of the stock (different poly count than other parts?).

![screen shot 11-07-17 at 04 21 pm](https://user-images.githubusercontent.com/16107012/32501253-d6a57b60-c3d7-11e7-905a-a1626c53add8.PNG)

**Comment by shadowmage45** [comment]
Yeah, it does, because it is (different poly/side count).  Not sure who modeled it (its the stock model)...but it is obviously wrong no matter what stock part you try and use it with.

I'll see what I can do about splitting off the one of the existing CM's heat-shield as a stand-alone model, and use that for the MHS part.  Sadly if/when I do, it will be potentially craft breaking due to the changes in geometry.

**Comment by Jimbodiah** [comment]
I think they didn't really care as they use that horrible shroud that sticks out.

A modular version of that HS you showed in your sstu topic would be awesome at some point in the future.

**Comment by shadowmage45** [comment]
Indeed, probably a good idea at this point, and simple enough to do (considering I already have a procedural heat-shield material created).

Have just mocked up some geometry for a stand-alone heat-shield part, will see about getting it all exported and included for the next release.

**Comment by shadowmage45** [comment]
Fixed; apparently I had 'increment * 0.5', rather than the intended 'increment * 0.05'.
