### ISSUE TITLE
Re-export tank models with fixed textures

### ISSUE THREAD

**Issue by taterkerman** [shadowmage45/SSTULabs#606]
`[LOG 20:36:32.628] Load(Model): SSTU/Assets/SC-TANK-A-7-0
[ERR 20:36:32.630] Texture 'SSTU/Assets/SC-TANKS-SLS-DIFF' not found!

[ERR 20:36:32.631] Texture 'SSTU/Assets/SC-TANKS-SLS-NRM' not found!

[LOG 20:36:32.632] Load(Model): SSTU/Assets/SC-TANK-A-7-5
[ERR 20:36:32.634] Texture 'SSTU/Assets/SC-TANKS-SLS-DIFF' not found!

[ERR 20:36:32.635] Texture 'SSTU/Assets/SC-TANKS-SLS-NRM' not found!

[LOG 20:36:32.636] Load(Model): SSTU/Assets/SC-TANK-A-8-0
[ERR 20:36:32.639] Texture 'SSTU/Assets/SC-TANKS-SLS-DIFF' not found!

[ERR 20:36:32.639] Texture 'SSTU/Assets/SC-TANKS-SLS-NRM' not found!

[LOG 20:36:32.640] Load(Model): SSTU/Assets/SC-TANK-B-0-5
[ERR 20:36:32.641] Texture 'SSTU/Assets/SC-TANKS-SLS-DIFF' not found!`

**Comment by taterkerman** [comment]
Like the above, except all the textures.
![error](https://user-images.githubusercontent.com/17967275/32761819-b175853a-c8b2-11e7-86d3-2c0cf1f3a6c0.png)

**Comment by shadowmage45** [comment]
Yep; that is because KSP is looking for the textures that were exported with those fuel-tank models.  Those particular textures have been gone a long time.

The solution is to re-export the models through Unity with a blank material / no textures assigned.

----

Do those parts/models still show up fine in-game?

**Comment by taterkerman** [comment]
This is the release you just posted on the forum, BTW.

**Comment by taterkerman** [comment]
The recoloring on all of them results in the same lockup I posted before.

Parts show up in game, just solid gray.
![gray](https://user-images.githubusercontent.com/17967275/32761882-29ba0d7c-c8b3-11e7-941a-af3480363c0a.png)

**Comment by shadowmage45** [comment]
Logs please; something is going on with your install that I'm not seeing on this end.
(seems like the shader/etc stuff is not being loaded properly)

(I get those same texture-missing error messages, they are normal)

**Comment by taterkerman** [comment]
I'll do a fresh install right now.

**Comment by shadowmage45** [comment]
Yeah; if it got installed on top of one of the old versions there will likely be problems due to the changes in naming/locations on a lot of things.  Some configs would end up getting duplicated that will cause the plugin to error out.

If that doesn't clean it up, please post up a KSP.log file (I think you can drag+drop them right in the reply box).  The log should have a bit of info on what/where things are going sideways.

(who knows, I could have packaged things up incorrectly, wouldn't be the first time)

**Comment by taterkerman** [comment]
I deleted everything (or at least I think I did). Maybe the EVE stuff threw me, except that EVE was working in that screen shot.

**Comment by taterkerman** [comment]
Works, I biffed it.

**Comment by shadowmage45** [comment]
Good to know :)

I'm going to leave this issue open as a reminder that I should re-export some parts to clean up those stock error messages.
