### ISSUE TITLE
Snapping docking ports?

### ISSUE THREAD

**Issue by taterkerman** [shadowmage45/SSTULabs#642]
The welding docking port can be set to snap (default is 90 degrees if turned on, and I honestly don't know what that angle actually means (question 1, lol).

Secondly, is the ability to force a snap a cfg issue that could be enabled on regular docking ports?

I was going to use the regular docking port as a way to attach saddle tanks on a thing I was building, but the angles are non-trivial. :) 

Looks like that angle stuff is the minrolldot stuff that is remarked out. I found a patch that adds snap angle to stock parts, I guess I can use that as the basis for what I need.

**Comment by shadowmage45** [comment]
> The welding docking port can be set to snap (default is 90 degrees if turned on, and I honestly don't know what that angle actually means (question 1, lol).

Honestly, neither do I.  Its a stock function/setting.  So it'll mean whatever it does when it is used on stock docking ports / other mods docking ports.  Whatever that is.

>Secondly, is the ability to force a snap a cfg issue that could be enabled on regular docking ports?

It is part of the stock docking node -- so just config stuff.

(the UI on the welding docking port is provided by SSTU, but all of the actual functions are part of the stock ModuleDockingNode)

>I was going to use the regular docking port as a way to attach saddle tanks on a thing I was building, but the angles are non-trivial. :)

I tentatively have something in mind for those -- a linear docking port part that has two internal docking ports, with special 'port type' specifications that ensure they will only dock with eachother/itself, and only in the proper orientation.

Of course, I got the part-module all written up, but I haven't had time to make new models to actually test the feature.  Probably had the module for 9-12 months.

Yes, I **really** need to find someone capable of doing modeling and texturing for SSTU parts, as I simply lack the time to do everything.  90% of the new stuff I want to do is simply held up for lack of time to create models/textures.   (the remaining 10% is stuff that is even not possible in KSP due to stock code or Unity limitations; doesn't stop me from wanting it though...)

**Comment by taterkerman** [comment]
There is a MM patch for adding this to stock parts, and it works fine with SSTU (I added the SSTU parts to the named list at the top of parts to affect):

![working](https://user-images.githubusercontent.com/17967275/33805999-57015bf2-dd7e-11e7-9887-c88260006568.png)

**Comment by Jimbodiah** [comment]
Do you mean snapping or welding? Can you share the patch?

**Comment by shadowmage45** [comment]
The snapping is what he is referring to.  Can 'easily' be added to any docking port equipped part through a patch.

The welding function could also be added to existing docking ports through a patch, but the code does not currently re-position things, so there would be a gap between the parts after welding.

**Comment by taterkerman** [comment]
Yeah, I was talking about angle snapping. This patch was in the thread about small patches over at the forum. I added the SSTU parts (the only change I made).

Not welding, because one of the benefits of "saddle tanks" would be the ability to drop them. The craft above would obviously be more efficient with just the center M1DV engine, but I figured an advantage would be a shorter burn, lol. That or I should have used hydrolox engines on the saddle tanks, done the Duna burn, then dumped them after they boiled off all the excess propellant. The above craft made Duna easily (lander docked to nose, and a small CFG hab in the middle). The remaining, center tank is almost full for the return trip.

[snaproll.cfg.zip](https://github.com/shadowmage45/SSTULabs/files/1545832/snaproll.cfg.zip)

**Comment by shadowmage45** [comment]
I've created a quick PartModule that can be added to docking-port equipped parts that will add two new UI controls:
* Snap Enabled (boolean - True / False toggle)
* Snap Angle - 0-360 degree selection, button/slider combo (e.g. the diameter scaling controls)

The PartModule itself will definitely be available with the next release.  ~Might also get it added to the existing stand-alone SSTU docking ports.~(done)  May be willing to patch the stock ports with this as well, as it is purely an 'enhancement' that should not interfere with any existing use of the parts.
