### ISSUE TITLE
Request: Recoloring on LC2 and LC3 Pods

### ISSUE THREAD

**Issue by KamikazeKricket** [shadowmage45/SSTULabs#648]
Both of the command modules for a lander have optional ascent tanks. Currently you cannot recolor theses ascent tanks. Now that the new lander descent stage tanks are nice and gold, I was wondering if it'd be possible that you could make the fuel tanks on the LC2 and LC3 pods color changeable as well so we can match with the gold of the new lander tanks.

Absolutely awesome work you guys have done.

**Comment by taterkerman** [comment]
The "you guys" are in fact just shadowmage. All this work.

The pods are being replaced at some point, but I'm unsure of the timing.

In the mean time, select the LC2/3 variant with no spherical tanks, then apply the tanks radially yourself, like so:
![lander](https://user-images.githubusercontent.com/17967275/33868163-9543dff2-debe-11e7-9315-272837bb6013.png)

**Comment by KamikazeKricket** [comment]
Cant believe I didn't think of that haha, thanks. 

Well props to Shadowimage. This is definitely my favorite mod. About 95% of my launches are all SSTU parts. I just love the fact that I can make a realistic looking Orion, SLS, and Soyuz. Absolutely fantastic.

**Comment by Jimbodiah** [comment]
Even something you come up with yourself can look realistic with SSTU. I'm loving the new PBR functionality and making sleek looking launchers for RSS. Having a blast making the gleaming torpedo tourist mission rocket for my career :)

![pbr_16](https://user-images.githubusercontent.com/16107012/33892767-f19f16b8-df59-11e7-829c-cab455d9477f.jpg)

**Comment by shadowmage45** [comment]
Indeed -- rather than spend time on recreating the textures for the current models, I would much rather spend that time on creating the -new- models and textures.

When created, they will fully support recoloring, and as a bonus, will likely have multiple 'external tank' options available.

Currently these are scheduled to be the next parts that are 'reworked', so... whenever I get enough patience to start working on modeling/texture stuff again, and pending KSP 1.4 development release timing.

**Comment by shadowmage45** [comment]
Will not be adding recoloring to the existing pod parts.  If/when they are reworked, it will come as part of the standard model development setup.
