### ISSUE TITLE
[Bug] RealPlume configs no longer work

### ISSUE THREAD

**Issue by pixe1reality** [shadowmage45/SSTULabs#675]
Due to an internal rewrite in RealPlume, the prior tag of
`:NEEDS[RealPlume&!RealismOverhaul]:BEFORE[RealPlume]`
does not work anymore.
I recommend replacing it with a tag like 
`:FOR[RealPlume]:NEEDS[SmokeScreen]`
which is how the Stock configs in RealPlume work. (I've replaced the :NEEDS tag with the :FOR tags shown here and everything works fine again, no need to rework the details)

**Comment by Jimbodiah** [comment]
Can you confirm that works? 

I can do the gruntwork for Mage and make a PR so he can continue relaxing ;)

**Comment by Jimbodiah** [comment]
BTW: I am running RealPlume-Stock v1.0.1 and have no issues. Is there a dev release?

**Comment by shadowmage45** [comment]
You cannot use FOR[RealPlume] in a patch, as this tells ModuleManager (and other mods) that RealPlume is present.  This then causes other mods using NEEDS[RealPlume] to think that RP is installed, so tons of things get patched regardless of if RP is actually present or not.  This alone has caused so very many support requests for me from **other mods** improperly using the FOR block.

So whatever the solution is, it will not be changing those patches to use FOR.  Because that is **wrong**.

**Comment by Jimbodiah** [comment]
Ah, that issue where engines seem to burn full throttle when they are not lit.

**Comment by pixe1reality** [comment]
In that case, I'll delete the custom patch I made. Something I feel is triggering the Realism Overhaul part of the config (despite me not having it installed), even with a base install with just SSTU, RealPlume and its dependencies.
Will try yet another clean install, to see if that fixes the derpiness.

**Comment by pixe1reality** [comment]
Error is on my end.
Thanks for highlighting the FOR block's use, because I copy-pasted a config for RO to spice up gameplay, and it had a FOR block. Next time, I should actually read the config before copy-pasting ._.
(that was stupid of me)

**Comment by Jimbodiah** [comment]
Hah, you should see the stuff I pulled off ;)

Mage told me the use for FOR recently as well, as I never knew when to use it. Hence the PR for all the ModIntegrations. Basically only use FOR when the patch is bundled with the actual mod, otherwise use NEEDS and AFTER.
