### ISSUE TITLE
MHS costs negative funds

### ISSUE THREAD

**Issue by pixe1reality** [shadowmage45/SSTULabs#717]
Something weird is happening to the MHS regarding part costs. At 0.625m diameter it costs negative funds, and scaling it up to about 2.5m makes it cost around 7 funds, then scaling it down again costs what seems to be normal cost scaling until you hit that 0.625m diameter.

**Comment by pixe1reality** [comment]
Unrelated, yet notable issue: the MFT-R cannot scale below 0.625m, and the MFT-R-01 model clips into whatever you attach it to, while the MFT-R-02 and 03 float off the attached object and also need adjusting.

**Comment by shadowmage45** [comment]
Can confirm the MHS issue.  Is actually quite an interesting little bit of weirdness that it does.

I have a feeling that this is being caused by the interaction between the VolumeContainer and MHS modules.  Will investigate further and should have it fixed for the next release.

---

MFT-R scaling - good catch, likely missing a part-upgrade or have an incorrect default value (or both...).

MFT-R rotation + offset - known issue (as with the MRCS blocks), but not sure I have it listed anywhere.  Have added it (and the above) to the running issues list for 1.4 testing versions.
