### ISSUE TITLE
SRB-U has negative mass at small diameter/length

### ISSUE THREAD

**Issue by blowfishpro** [shadowmage45/SSTULabs#733]
Seems pretty reproducable, let me know if this needs more info

**Comment by shadowmage45** [comment]
Definitely an issue - most likely cause is improperly specified values in the model defs.... but these parts are incredibly complex, so could be any of a number of other sources.

As long as it can be repro'd though, shouldn't be a problem to track it down and clean it up.

**Comment by shadowmage45** [comment]
Error was being caused by the VolumeContainer module also zeroing out the default part mass/cost.

Have changed the configs for VolumeContainer on the SRB-U, SRB-A, and MFT-A to make sure that the ModularPart module is the only thing zeroing the default mass/cost values.

Have verified that they no longer have negative mass values at small diameter/length selections.

![screenshot6](https://user-images.githubusercontent.com/1503399/45847236-9fd7fe00-bce7-11e8-8004-a20b93e27723.png)
