### ISSUE TITLE
SRB-U - top interstage node is in the wrong place

### ISSUE THREAD

**Issue by blowfishpro** [shadowmage45/SSTULabs#737]
It's in the same place as the other top node rather than at the bottom of the dome.  The mount interstage node is fine

**Comment by shadowmage45** [comment]
Good catch -- does this effect only specific nose selections, or is it with every selection?
(specific noses = model def config issues, all noses = likely a plugin code problem)

**Comment by shadowmage45** [comment]
Interestingly enough this appears to be being caused by an interaction between the model-definition setup for this part, where it is erroneously pulling the 'top fairing bottom' position from the 'nose' model slot rather than the 'upper' model slot.

But even more interestingly... the same function is called to set up the fairing positions, and yet it returns the proper model-module and position value (the top fairing works fine on the SRB-U)

**Comment by shadowmage45** [comment]
Arghh... typos FTL --   node != nose....

Seems to be fixed; should also fix any similar issues with the MUS and/or other parts using the SSTUModularPart module.

![screenshot5](https://user-images.githubusercontent.com/1503399/45845558-b62f8b00-bce2-11e8-96cd-598ae12c91db.png)
