### ISSUE TITLE
Interstage petal adapter petals re-appear after switch back from KSC

### ISSUE THREAD

**Issue by Joker58th** [shadowmage45/SSTULabs#759]
Clean KSP 1.5.1 install
SSTU 0.9.44.156
GameData folder shown in imgur album

Steps to reproduce:
1. Add probe core and interstage petal adapter
2. Configure petal adapter as shown in screen shot
3. Launch
4. Stage the petal adapter (petals detach and fall away)
5. Return to space center without recovering
6. Go back to vessel by using "Fly" or tracking station

The petals return with no way to removing them again. 

Desired solution:
The petals need to stay gone once detached.

[output_log.txt](https://github.com/shadowmage45/SSTULabs/files/2641572/output_log.txt)

https://imgur.com/a/3IHd5Zj

**Comment by shadowmage45** [comment]
You are correct -- if you jettison the panels, they should stay gone if/when that craft is reloaded.  If it is not doing so, there is definitely a bug at play.

Will investigate, and should be able to have fixed up for the next release.

**Comment by shadowmage45** [comment]
Interestingly, this appears to be caused by interactions when the 'deploy rotation' is set specifically to zero, where a rotation of zero in the code is often used to denote 'retracted'.

May need to implement more robust state handling, as the current functionality of the part far exceeds what was in the original design specifications, much of which apparently was not properly integrated.
