### ISSUE TITLE
GEN-MRCS scaling issues

### ISSUE THREAD

**Issue by taterkerman** [shadowmage45/SSTULabs#761]
The scaling function is awesome, but the various (stand-in) structures don't scale/match, and perhaps more importantly, the regular RCS block can be buried in the tank.

Take a standard 1.25m MFT-A, and place a  4F, 4A or 5F-V block of the RCS on the tank. The bells are 50% buried in the tank.

When I started this I thought it was a scaling thing, but it doesn't seem to matter. Unsure how to edit title.

**Comment by shadowmage45** [comment]
Basically -- the part has never been finished.  I need proper data for the structures... which is damn difficult to get for stock models (because I don't have easy access to the raw models, only the binary compiled .mu files).

I need model data for the standoff models, and the RCS blocks themselves (width, length, height, origin/offset from origin).  Until I can get that data... things will be incorrect.  And my motivation for digging into stuff like this is pretty much zero as-of late (will take 1-2 hours just to get started, and then ~>30 minutes more _per model_ to extract the parameters) -- so basically like 8+ hours of work, to fix one part...  mostly because stock can't use their models consistently (scales/etc are not consistent).  I haven't had 8 uninterrupted hours of modeling time available to me in... months, and don't expect that the situation will be changing anytime soon.

**Comment by taterkerman** [comment]
Gotcha. Having a chance to actually play is new for the last few months for me, so I thought I'd let you know what I have found that's not working.

**Comment by shadowmage45** [comment]
No worries; at the very least it is good to have an issue ticket to keep track of these and let others know that it has already been reported.

Hoping to be able to get back into active modding eventually, but can't really say when that will be.

**Comment by shadowmage45** [comment]
Doing some further investigation/fixing into this.

Mostly it has been cleaned up by fixing up the model position offsets in the model definitions.  This fixes it so that the RCS blocks sit where they are supposed to (mostly), both in stand-alone, and when the structures are in use.

Digging a bit further, it looks like I need to update the SSTUModularRCS PartModule in order to utilize the RCS block model definition specified surface attach node when no structure is in use.  Currently that data is unused by that module, but should be _relatively simple_ to fix.

At the very least the model-definition offsets have been fixed, as well as fixing up some issues with some of the stand-off model definitions (the -A was missing its model due to the stock fuel tank model updates).  Should all be available with the next release.
