### ISSUE TITLE
Textures are missed

### ISSUE THREAD

**Issue by Komakyo** [shadowmage45/SSTULabs#786]
All metalic like textures turn black
![KSP_x64_2019-05-30_14-51-09](https://user-images.githubusercontent.com/46266786/58641261-26bf8a80-82fb-11e9-96a2-31ca64516b9a.png)
I dont know what's going on.
I retried without the others mods (only the dependencies of SSTU) and its doing the same things. Its only a graphic bug since I can combine parts without issues.
![KSP_x64_2019-05-30_15-10-07](https://user-images.githubusercontent.com/46266786/58641434-79994200-82fb-11e9-8756-aed320e9c776.png)
I also reduced the graphics settings to see if it was the memory which was unable to load all the textures but got the same result.

**Comment by shadowmage45** [comment]
This is being caused by reflections being disabled or unsupported.  Likely either an installation error, or other config or loading error, is preventing the reflection system from being used -- by default things reflect 'nothing', which is seen as being 'black'.

Please upload/attach/link to a copy of your KSP.log file -- this file should contain the information needed in order to determine the cause of the problem.

**Comment by Komakyo** [comment]
Okay.
[KSP.log](https://github.com/shadowmage45/SSTULabs/files/3238564/KSP.log)

**Comment by Komakyo** [comment]
Problem resolved
Its render quality settings, I put it in "most fluid", and when I put it in "fantastic" the problem was resolved. 
![KSP_x64_2019-05-30_22-27-25](https://user-images.githubusercontent.com/46266786/58662298-28547700-832a-11e9-8a72-2eab88d7ff90.jpg)

Thanks for the response.
