### ISSUE TITLE
Integrated seperatron

### ISSUE THREAD

**Issue by Jimbodiah** [shadowmage45/SSTULabs#86]
Seperatron functionality for main tanks in the decoupler ring. Mentioned on the forum but can't find anything by the description here.

**Comment by shadowmage45** [comment]
Honestly, I -don't- want separation motors on every tank.  Not everyone will need them, nor want them; and even if they -do- want them, they might not want-stack based jettison motors, but radial jettison motors.

No problem with the concept, as it is something that could be of use, but it cannot just be a blanket 'all tanks have standard retro-rockets' type setup.

**IF** I implement this, it would have to be as a toggle-able-module (not really possible due to stock engine module limitations/problems with other mod compatibility/inability to add/remove modules at run-time), or as a completely separate part (sub-optimal, as I would like to avoid creating yet-more-editor parts for such minor differences, especially when I might yet have more tank variants coming, and don't want to duplicate those as well just for retro-rockets).  Neither of those is something I really want to deal with or implement.

Going to leave open for now, as I might be able to come across an acceptable implementation method in the near future.  However if I cannot find any solution within a couple of weeks, will likely be closed as 'unsolvable'.

As an alternative, as I had stated, I am planning an interstage-decoupler part.  This would take the place of an engine fairing, while providing:
- Lower node decoupler; decouples the engine from the tank below
- Ullage rockets (rather than retro on the discarded tank, use ullage on the -active- stage)
- Upper node decoupler - to decouple the decoupler after retro-rockets have been used.

**Comment by Jimbodiah** [comment]
Adding to the tanks is not a good idea I think, rather the decoupler ring or a new part (ring) that you can stick on before or after the decoupler (or both). Now it's 3-6 parts, would be reduced to 1. I use them on almost every large rocket to get the prior stage away from the next one while freefloating, looks half-assed with those seperatrons on the side.

**Comment by shadowmage45** [comment]
Rolling this into #92 
It should serve your purposes; though you may need two of them if you want both retro and ullage rockets.

**Comment by Jimbodiah** [comment]
one would be fine. thanks a million!
