### ISSUE TITLE
Customizable/modular parts - implement IMassModifier

### ISSUE THREAD

**Issue by shadowmage45** [shadowmage45/SSTULabs#87]
The module -appears- to function correctly now, passing in only the prefab part default mass.  

Proper use to override a parts mass completely is

```
return -defaultMass + newMass;
```
## TODO:
- SSTUModuleSwitch - will wait until LC refresh; the current in-place method -appears- to work, last checked
## DONE:
- SSTUModularFuelTank
- SSTUCustomUpperStage
- SSTUProceduralDecoupler
- SSTUInterstageFairing

**Comment by blowfishpro** [comment]
It still doesn't affect physics, which was _supposed_ to be its original intention.  This may change in 1.1.

The last time I checked, the engineer report used prefab mass + module masses (passing in the prefab mass), but some mods work differently, e.g. RCS build Aid uses the full part mass rather than the prefab mass.

**Comment by shadowmage45** [comment]
Hehe, good thing I'm still 'hacking' it then, and manually setting the part-mass from the plugin (for now anyway).

IIRC previously, it would pass in the prefab part mass to the first module, and then the new 'total' mass for subsequent modules

Sounds like I will still not be able to properly implement using the interface for the LanderCore module-switched parts; but as long as it is working for the fuel-tank and single-module procedural parts, will be a good improvement for now.

Mostly, I want to insure that the parts are usable in career mode with its mass/size limitations.
